// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: gateway/v1/cache/rate_limit.proto

package gatewaycache

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RateLimitBucket represents a rate limit bucket for tracking API usage
// Stored in: rate_limit:{tenant_id}:{user_id}:{endpoint} (Redis String with counter)
// Also can use: rate_limit_bucket:{bucket_id} (Redis Hash) for more complex scenarios
type RateLimitBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketId      string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method"`
	TokensUsed    int32                  `protobuf:"varint,7,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used"`
	TokensLimit   int32                  `protobuf:"varint,8,opt,name=tokens_limit,json=tokensLimit,proto3" json:"tokens_limit"`
	WindowStart   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=window_start,json=windowStart,proto3" json:"window_start"`
	WindowEnd     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=window_end,json=windowEnd,proto3" json:"window_end"`
	ResetAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=reset_at,json=resetAt,proto3" json:"reset_at"`
	Blocked       bool                   `protobuf:"varint,12,opt,name=blocked,proto3" json:"blocked"`
	BlockedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=blocked_at,json=blockedAt,proto3" json:"blocked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitBucket) Reset() {
	*x = RateLimitBucket{}
	mi := &file_gateway_v1_cache_rate_limit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitBucket) ProtoMessage() {}

func (x *RateLimitBucket) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_rate_limit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitBucket.ProtoReflect.Descriptor instead.
func (*RateLimitBucket) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_rate_limit_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitBucket) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *RateLimitBucket) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RateLimitBucket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RateLimitBucket) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RateLimitBucket) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RateLimitBucket) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RateLimitBucket) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *RateLimitBucket) GetTokensLimit() int32 {
	if x != nil {
		return x.TokensLimit
	}
	return 0
}

func (x *RateLimitBucket) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *RateLimitBucket) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *RateLimitBucket) GetResetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetAt
	}
	return nil
}

func (x *RateLimitBucket) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *RateLimitBucket) GetBlockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BlockedAt
	}
	return nil
}

// RateLimitRule represents a rate limiting rule configuration
// Stored in: rate_limit_rules:{tenant_id}:{rule_id} (Redis Hash)
// Or cached from database: rate_limit_rule_cache:{rule_id}
type RateLimitRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit"`
	Window        *durationpb.Duration   `protobuf:"bytes,7,opt,name=window,proto3" json:"window"`
	Scope         string                 `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope"`
	Priority      int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled"`
	CachedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRule) Reset() {
	*x = RateLimitRule{}
	mi := &file_gateway_v1_cache_rate_limit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRule) ProtoMessage() {}

func (x *RateLimitRule) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_rate_limit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRule.ProtoReflect.Descriptor instead.
func (*RateLimitRule) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_rate_limit_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RateLimitRule) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RateLimitRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RateLimitRule) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RateLimitRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RateLimitRule) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RateLimitRule) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *RateLimitRule) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RateLimitRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RateLimitRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RateLimitRule) GetCachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CachedAt
	}
	return nil
}

// RateLimitViolation represents a rate limit violation event
// Stored in: rate_limit_violations:{tenant_id}:{user_id} (Redis Sorted Set, score = timestamp)
type RateLimitViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViolationId   string                 `protobuf:"bytes,1,opt,name=violation_id,json=violationId,proto3" json:"violation_id"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method"`
	RuleId        string                 `protobuf:"bytes,7,opt,name=rule_id,json=ruleId,proto3" json:"rule_id"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp"`
	RequestId     string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitViolation) Reset() {
	*x = RateLimitViolation{}
	mi := &file_gateway_v1_cache_rate_limit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitViolation) ProtoMessage() {}

func (x *RateLimitViolation) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_rate_limit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitViolation.ProtoReflect.Descriptor instead.
func (*RateLimitViolation) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_rate_limit_proto_rawDescGZIP(), []int{2}
}

func (x *RateLimitViolation) GetViolationId() string {
	if x != nil {
		return x.ViolationId
	}
	return ""
}

func (x *RateLimitViolation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RateLimitViolation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RateLimitViolation) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RateLimitViolation) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RateLimitViolation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RateLimitViolation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RateLimitViolation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RateLimitViolation) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_gateway_v1_cache_rate_limit_proto protoreflect.FileDescriptor

const file_gateway_v1_cache_rate_limit_proto_rawDesc = "" +
	"\n" +
	"!gateway/v1/cache/rate_limit.proto\x12\x10gateway.v1.cache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x13tagger/tagger.proto\"\xcc\x06\n" +
	"\x0fRateLimitBucket\x122\n" +
	"\tbucket_id\x18\x01 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"bucket_id\"R\bbucketId\x122\n" +
	"\ttenant_id\x18\x02 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"tenant_id\"R\btenantId\x126\n" +
	"\auser_id\x18\x03 \x01(\tB\x1d\x9a\x84\x9e\x03\x18json:\"user_id,omitempty\"R\x06userId\x12?\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tB \x9a\x84\x9e\x03\x1bjson:\"ip_address,omitempty\"R\tipAddress\x120\n" +
	"\bendpoint\x18\x05 \x01(\tB\x14\x9a\x84\x9e\x03\x0fjson:\"endpoint\"R\bendpoint\x12*\n" +
	"\x06method\x18\x06 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"method\"R\x06method\x128\n" +
	"\vtokens_used\x18\a \x01(\x05B\x17\x9a\x84\x9e\x03\x12json:\"tokens_used\"R\n" +
	"tokensUsed\x12;\n" +
	"\ftokens_limit\x18\b \x01(\x05B\x18\x9a\x84\x9e\x03\x13json:\"tokens_limit\"R\vtokensLimit\x12W\n" +
	"\fwindow_start\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x18\x9a\x84\x9e\x03\x13json:\"window_start\"R\vwindowStart\x12Q\n" +
	"\n" +
	"window_end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"window_end\"R\twindowEnd\x12K\n" +
	"\breset_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x14\x9a\x84\x9e\x03\x0fjson:\"reset_at\"R\aresetAt\x12-\n" +
	"\ablocked\x18\f \x01(\bB\x13\x9a\x84\x9e\x03\x0ejson:\"blocked\"R\ablocked\x12[\n" +
	"\n" +
	"blocked_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampB \x9a\x84\x9e\x03\x1bjson:\"blocked_at,omitempty\"R\tblockedAt\"\xbf\x04\n" +
	"\rRateLimitRule\x12,\n" +
	"\arule_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"rule_id\"R\x06ruleId\x122\n" +
	"\ttenant_id\x18\x02 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"tenant_id\"R\btenantId\x12$\n" +
	"\x04name\x18\x03 \x01(\tB\x10\x9a\x84\x9e\x03\vjson:\"name\"R\x04name\x120\n" +
	"\bendpoint\x18\x04 \x01(\tB\x14\x9a\x84\x9e\x03\x0fjson:\"endpoint\"R\bendpoint\x12*\n" +
	"\x06method\x18\x05 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"method\"R\x06method\x12'\n" +
	"\x05limit\x18\x06 \x01(\x05B\x11\x9a\x84\x9e\x03\fjson:\"limit\"R\x05limit\x12E\n" +
	"\x06window\x18\a \x01(\v2\x19.google.protobuf.DurationB\x12\x9a\x84\x9e\x03\rjson:\"window\"R\x06window\x12'\n" +
	"\x05scope\x18\b \x01(\tB\x11\x9a\x84\x9e\x03\fjson:\"scope\"R\x05scope\x120\n" +
	"\bpriority\x18\t \x01(\x05B\x14\x9a\x84\x9e\x03\x0fjson:\"priority\"R\bpriority\x12-\n" +
	"\aenabled\x18\n" +
	" \x01(\bB\x13\x9a\x84\x9e\x03\x0ejson:\"enabled\"R\aenabled\x12N\n" +
	"\tcached_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x15\x9a\x84\x9e\x03\x10json:\"cached_at\"R\bcachedAt\"\x92\x04\n" +
	"\x12RateLimitViolation\x12;\n" +
	"\fviolation_id\x18\x01 \x01(\tB\x18\x9a\x84\x9e\x03\x13json:\"violation_id\"R\vviolationId\x122\n" +
	"\ttenant_id\x18\x02 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"tenant_id\"R\btenantId\x126\n" +
	"\auser_id\x18\x03 \x01(\tB\x1d\x9a\x84\x9e\x03\x18json:\"user_id,omitempty\"R\x06userId\x125\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"ip_address\"R\tipAddress\x120\n" +
	"\bendpoint\x18\x05 \x01(\tB\x14\x9a\x84\x9e\x03\x0fjson:\"endpoint\"R\bendpoint\x12*\n" +
	"\x06method\x18\x06 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"method\"R\x06method\x12,\n" +
	"\arule_id\x18\a \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"rule_id\"R\x06ruleId\x12O\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x15\x9a\x84\x9e\x03\x10json:\"timestamp\"R\ttimestamp\x12?\n" +
	"\n" +
	"request_id\x18\t \x01(\tB \x9a\x84\x9e\x03\x1bjson:\"request_id,omitempty\"R\trequestIdBBZ@erp.localhost/internal/infra/model/gateway/v1/cache;gatewaycacheb\x06proto3"

var (
	file_gateway_v1_cache_rate_limit_proto_rawDescOnce sync.Once
	file_gateway_v1_cache_rate_limit_proto_rawDescData []byte
)

func file_gateway_v1_cache_rate_limit_proto_rawDescGZIP() []byte {
	file_gateway_v1_cache_rate_limit_proto_rawDescOnce.Do(func() {
		file_gateway_v1_cache_rate_limit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_cache_rate_limit_proto_rawDesc), len(file_gateway_v1_cache_rate_limit_proto_rawDesc)))
	})
	return file_gateway_v1_cache_rate_limit_proto_rawDescData
}

var file_gateway_v1_cache_rate_limit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_v1_cache_rate_limit_proto_goTypes = []any{
	(*RateLimitBucket)(nil),       // 0: gateway.v1.cache.RateLimitBucket
	(*RateLimitRule)(nil),         // 1: gateway.v1.cache.RateLimitRule
	(*RateLimitViolation)(nil),    // 2: gateway.v1.cache.RateLimitViolation
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 4: google.protobuf.Duration
}
var file_gateway_v1_cache_rate_limit_proto_depIdxs = []int32{
	3, // 0: gateway.v1.cache.RateLimitBucket.window_start:type_name -> google.protobuf.Timestamp
	3, // 1: gateway.v1.cache.RateLimitBucket.window_end:type_name -> google.protobuf.Timestamp
	3, // 2: gateway.v1.cache.RateLimitBucket.reset_at:type_name -> google.protobuf.Timestamp
	3, // 3: gateway.v1.cache.RateLimitBucket.blocked_at:type_name -> google.protobuf.Timestamp
	4, // 4: gateway.v1.cache.RateLimitRule.window:type_name -> google.protobuf.Duration
	3, // 5: gateway.v1.cache.RateLimitRule.cached_at:type_name -> google.protobuf.Timestamp
	3, // 6: gateway.v1.cache.RateLimitViolation.timestamp:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_gateway_v1_cache_rate_limit_proto_init() }
func file_gateway_v1_cache_rate_limit_proto_init() {
	if File_gateway_v1_cache_rate_limit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_cache_rate_limit_proto_rawDesc), len(file_gateway_v1_cache_rate_limit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_cache_rate_limit_proto_goTypes,
		DependencyIndexes: file_gateway_v1_cache_rate_limit_proto_depIdxs,
		MessageInfos:      file_gateway_v1_cache_rate_limit_proto_msgTypes,
	}.Build()
	File_gateway_v1_cache_rate_limit_proto = out.File
	file_gateway_v1_cache_rate_limit_proto_goTypes = nil
	file_gateway_v1_cache_rate_limit_proto_depIdxs = nil
}
