// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth/v1/rbac.proto

package authv1

import (
	v1 "erp.localhost/internal/infra/model/infra/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                   // User to assign roles to
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`          // Role IDs to assign
	AssignedBy    string                 `protobuf:"bytes,3,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"` // Who is assigning the roles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesRequest) Reset() {
	*x = AssignRolesRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesRequest) ProtoMessage() {}

func (x *AssignRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesRequest.ProtoReflect.Descriptor instead.
func (*AssignRolesRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *AssignRolesRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *AssignRolesRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *AssignRolesRequest) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

type RemoveRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                // User to remove roles from
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`       // Role IDs to remove
	RemovedBy     string                 `protobuf:"bytes,3,opt,name=removed_by,json=removedBy,proto3" json:"removed_by,omitempty"` // Who is removing the roles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRolesRequest) Reset() {
	*x = RemoveRolesRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRolesRequest) ProtoMessage() {}

func (x *RemoveRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRolesRequest.ProtoReflect.Descriptor instead.
func (*RemoveRolesRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveRolesRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *RemoveRolesRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *RemoveRolesRequest) GetRemovedBy() string {
	if x != nil {
		return x.RemovedBy
	}
	return ""
}

// Role Service Messages
type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // Requestor identity
	Role          *Role                  `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`             // Role data to create
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoleRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *CreateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // Requestor identity
	Role          *Role                  `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`             // Role data to update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *UpdateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                                 // Requestor identity
	RoleId         string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                           // Role ID to retrieve
	TargetTenantId string                 `protobuf:"bytes,3,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"` // Target tenant (for cross-tenant operations)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoleRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *GetRoleRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

type ListRolesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                                 // Requestor identity
	TargetTenantId string                 `protobuf:"bytes,2,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"` // Target tenant (for cross-tenant operations)
	Pagination     *v1.PaginationRequest  `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{6}
}

func (x *ListRolesRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *ListRolesRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

func (x *ListRolesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{7}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DeleteRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                                 // Requestor identity
	RoleId         string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                           // Role ID to delete
	TargetTenantId string                 `protobuf:"bytes,3,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"` // Target tenant (for cross-tenant operations)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoleRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *DeleteRoleRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

// Permission Service Messages
type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // Requestor identity
	Permission    *Permission            `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"` // Permission data to create
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePermissionRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *CreatePermissionRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  string                 `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePermissionResponse) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // Requestor identity
	Permission    *Permission            `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"` // Permission data to update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePermissionRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *UpdatePermissionRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type GetPermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                                 // Requestor identity
	PermissionId   string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`         // Permission ID to retrieve
	TargetTenantId string                 `protobuf:"bytes,3,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"` // Target tenant (for cross-tenant operations)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{12}
}

func (x *GetPermissionRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *GetPermissionRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

type ListPermissionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                                 // Requestor identity
	TargetTenantId string                 `protobuf:"bytes,2,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"` // Target tenant (for cross-tenant operations)
	Pagination     *v1.PaginationRequest  `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{13}
}

func (x *ListPermissionsRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *ListPermissionsRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

func (x *ListPermissionsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{14}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListPermissionsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DeletePermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                                 // Requestor identity
	PermissionId   string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`         // Permission ID to delete
	TargetTenantId string                 `protobuf:"bytes,3,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"` // Target tenant (for cross-tenant operations)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{15}
}

func (x *DeletePermissionRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *DeletePermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *DeletePermissionRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

// Verification Service Messages
type CheckPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`   // User to check
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"` // Permissions to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsRequest) Reset() {
	*x = CheckPermissionsRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsRequest) ProtoMessage() {}

func (x *CheckPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{16}
}

func (x *CheckPermissionsRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *CheckPermissionsRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CheckPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   map[string]bool        `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Map of permission -> has_permission
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsResponse) Reset() {
	*x = CheckPermissionsResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsResponse) ProtoMessage() {}

func (x *CheckPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{17}
}

func (x *CheckPermissionsResponse) GetPermissions() map[string]bool {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type HasPermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                                 // User to check
	Permission     string                 `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`                                 // Permission to check
	TargetTenantId string                 `protobuf:"bytes,3,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"` // Target tenant (for cross-tenant operations)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HasPermissionRequest) Reset() {
	*x = HasPermissionRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionRequest) ProtoMessage() {}

func (x *HasPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionRequest.ProtoReflect.Descriptor instead.
func (*HasPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{18}
}

func (x *HasPermissionRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *HasPermissionRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *HasPermissionRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

type HasPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPermission bool                   `protobuf:"varint,1,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPermissionResponse) Reset() {
	*x = HasPermissionResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionResponse) ProtoMessage() {}

func (x *HasPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionResponse.ProtoReflect.Descriptor instead.
func (*HasPermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{19}
}

func (x *HasPermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // User to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserPermissionsRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   map[string]bool        `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Map of all user permissions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserPermissionsResponse) GetPermissions() map[string]bool {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *v1.UserIdentifier     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // User to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserRolesRequest) GetIdentifier() *v1.UserIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleIds       []string               `protobuf:"bytes,1,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"` // List of role IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserRolesResponse) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type IsSystemTenantUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Tenant ID to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSystemTenantUserRequest) Reset() {
	*x = IsSystemTenantUserRequest{}
	mi := &file_auth_v1_rbac_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSystemTenantUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSystemTenantUserRequest) ProtoMessage() {}

func (x *IsSystemTenantUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSystemTenantUserRequest.ProtoReflect.Descriptor instead.
func (*IsSystemTenantUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{24}
}

func (x *IsSystemTenantUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type IsSystemTenantUserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsSystemTenant bool                   `protobuf:"varint,1,opt,name=is_system_tenant,json=isSystemTenant,proto3" json:"is_system_tenant,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsSystemTenantUserResponse) Reset() {
	*x = IsSystemTenantUserResponse{}
	mi := &file_auth_v1_rbac_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSystemTenantUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSystemTenantUserResponse) ProtoMessage() {}

func (x *IsSystemTenantUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rbac_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSystemTenantUserResponse.ProtoReflect.Descriptor instead.
func (*IsSystemTenantUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rbac_proto_rawDescGZIP(), []int{25}
}

func (x *IsSystemTenantUserResponse) GetIsSystemTenant() bool {
	if x != nil {
		return x.IsSystemTenant
	}
	return false
}

var File_auth_v1_rbac_proto protoreflect.FileDescriptor

const file_auth_v1_rbac_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/rbac.proto\x12\aauth.v1\x1a\x14infra/v1/infra.proto\x1a\x12auth/v1/role.proto\x1a\x18auth/v1/permission.proto\"\x8a\x01\n" +
	"\x12AssignRolesRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\x12\x1f\n" +
	"\vassigned_by\x18\x03 \x01(\tR\n" +
	"assignedBy\"\x88\x01\n" +
	"\x12RemoveRolesRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\x12\x1d\n" +
	"\n" +
	"removed_by\x18\x03 \x01(\tR\tremovedBy\"p\n" +
	"\x11CreateRoleRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12!\n" +
	"\x04role\x18\x02 \x01(\v2\r.auth.v1.RoleR\x04role\"-\n" +
	"\x12CreateRoleResponse\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"p\n" +
	"\x11UpdateRoleRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12!\n" +
	"\x04role\x18\x02 \x01(\v2\r.auth.v1.RoleR\x04role\"\x8d\x01\n" +
	"\x0eGetRoleRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12(\n" +
	"\x10target_tenant_id\x18\x03 \x01(\tR\x0etargetTenantId\"\xc7\x01\n" +
	"\x10ListRolesRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12(\n" +
	"\x10target_tenant_id\x18\x02 \x01(\tR\x0etargetTenantId\x12@\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1b.infra.v1.PaginationRequestH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"v\n" +
	"\x11ListRolesResponse\x12#\n" +
	"\x05roles\x18\x01 \x03(\v2\r.auth.v1.RoleR\x05roles\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.infra.v1.PaginationResponseR\n" +
	"pagination\"\x90\x01\n" +
	"\x11DeleteRoleRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12(\n" +
	"\x10target_tenant_id\x18\x03 \x01(\tR\x0etargetTenantId\"\x88\x01\n" +
	"\x17CreatePermissionRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x123\n" +
	"\n" +
	"permission\x18\x02 \x01(\v2\x13.auth.v1.PermissionR\n" +
	"permission\"?\n" +
	"\x18CreatePermissionResponse\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\"\x88\x01\n" +
	"\x17UpdatePermissionRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x123\n" +
	"\n" +
	"permission\x18\x02 \x01(\v2\x13.auth.v1.PermissionR\n" +
	"permission\"\x9f\x01\n" +
	"\x14GetPermissionRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\x12(\n" +
	"\x10target_tenant_id\x18\x03 \x01(\tR\x0etargetTenantId\"\xcd\x01\n" +
	"\x16ListPermissionsRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12(\n" +
	"\x10target_tenant_id\x18\x02 \x01(\tR\x0etargetTenantId\x12@\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1b.infra.v1.PaginationRequestH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"\x8e\x01\n" +
	"\x17ListPermissionsResponse\x125\n" +
	"\vpermissions\x18\x01 \x03(\v2\x13.auth.v1.PermissionR\vpermissions\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.infra.v1.PaginationResponseR\n" +
	"pagination\"\xa2\x01\n" +
	"\x17DeletePermissionRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\x12(\n" +
	"\x10target_tenant_id\x18\x03 \x01(\tR\x0etargetTenantId\"u\n" +
	"\x17CheckPermissionsRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\xb0\x01\n" +
	"\x18CheckPermissionsResponse\x12T\n" +
	"\vpermissions\x18\x01 \x03(\v22.auth.v1.CheckPermissionsResponse.PermissionsEntryR\vpermissions\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x14HasPermissionRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\x12(\n" +
	"\x10target_tenant_id\x18\x03 \x01(\tR\x0etargetTenantId\">\n" +
	"\x15HasPermissionResponse\x12%\n" +
	"\x0ehas_permission\x18\x01 \x01(\bR\rhasPermission\"U\n" +
	"\x19GetUserPermissionsRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\"\xb4\x01\n" +
	"\x1aGetUserPermissionsResponse\x12V\n" +
	"\vpermissions\x18\x01 \x03(\v24.auth.v1.GetUserPermissionsResponse.PermissionsEntryR\vpermissions\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"O\n" +
	"\x13GetUserRolesRequest\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.infra.v1.UserIdentifierR\n" +
	"identifier\"1\n" +
	"\x14GetUserRolesResponse\x12\x19\n" +
	"\brole_ids\x18\x01 \x03(\tR\aroleIds\"8\n" +
	"\x19IsSystemTenantUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"F\n" +
	"\x1aIsSystemTenantUserResponse\x12(\n" +
	"\x10is_system_tenant\x18\x01 \x01(\bR\x0eisSystemTenant2\xc7\x02\n" +
	"\vRoleService\x12E\n" +
	"\n" +
	"CreateRole\x12\x1a.auth.v1.CreateRoleRequest\x1a\x1b.auth.v1.CreateRoleResponse\x12<\n" +
	"\n" +
	"UpdateRole\x12\x1a.auth.v1.UpdateRoleRequest\x1a\x12.infra.v1.Response\x121\n" +
	"\aGetRole\x12\x17.auth.v1.GetRoleRequest\x1a\r.auth.v1.Role\x12B\n" +
	"\tListRoles\x12\x19.auth.v1.ListRolesRequest\x1a\x1a.auth.v1.ListRolesResponse\x12<\n" +
	"\n" +
	"DeleteRole\x12\x1a.auth.v1.DeleteRoleRequest\x1a\x12.infra.v1.Response2\x9b\x03\n" +
	"\x11PermissionService\x12W\n" +
	"\x10CreatePermission\x12 .auth.v1.CreatePermissionRequest\x1a!.auth.v1.CreatePermissionResponse\x12H\n" +
	"\x10UpdatePermission\x12 .auth.v1.UpdatePermissionRequest\x1a\x12.infra.v1.Response\x12C\n" +
	"\rGetPermission\x12\x1d.auth.v1.GetPermissionRequest\x1a\x13.auth.v1.Permission\x12T\n" +
	"\x0fListPermissions\x12\x1f.auth.v1.ListPermissionsRequest\x1a .auth.v1.ListPermissionsResponse\x12H\n" +
	"\x10DeletePermission\x12 .auth.v1.DeletePermissionRequest\x1a\x12.infra.v1.Response2\xc9\x03\n" +
	"\x13VerificationService\x12W\n" +
	"\x10CheckPermissions\x12 .auth.v1.CheckPermissionsRequest\x1a!.auth.v1.CheckPermissionsResponse\x12N\n" +
	"\rHasPermission\x12\x1d.auth.v1.HasPermissionRequest\x1a\x1e.auth.v1.HasPermissionResponse\x12]\n" +
	"\x12GetUserPermissions\x12\".auth.v1.GetUserPermissionsRequest\x1a#.auth.v1.GetUserPermissionsResponse\x12K\n" +
	"\fGetUserRoles\x12\x1c.auth.v1.GetUserRolesRequest\x1a\x1d.auth.v1.GetUserRolesResponse\x12]\n" +
	"\x12IsSystemTenantUser\x12\".auth.v1.IsSystemTenantUserRequest\x1a#.auth.v1.IsSystemTenantUserResponseB3Z1erp.localhost/internal/infra/model/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_rbac_proto_rawDescOnce sync.Once
	file_auth_v1_rbac_proto_rawDescData []byte
)

func file_auth_v1_rbac_proto_rawDescGZIP() []byte {
	file_auth_v1_rbac_proto_rawDescOnce.Do(func() {
		file_auth_v1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_rbac_proto_rawDesc), len(file_auth_v1_rbac_proto_rawDesc)))
	})
	return file_auth_v1_rbac_proto_rawDescData
}

var file_auth_v1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_auth_v1_rbac_proto_goTypes = []any{
	(*AssignRolesRequest)(nil),         // 0: auth.v1.AssignRolesRequest
	(*RemoveRolesRequest)(nil),         // 1: auth.v1.RemoveRolesRequest
	(*CreateRoleRequest)(nil),          // 2: auth.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),         // 3: auth.v1.CreateRoleResponse
	(*UpdateRoleRequest)(nil),          // 4: auth.v1.UpdateRoleRequest
	(*GetRoleRequest)(nil),             // 5: auth.v1.GetRoleRequest
	(*ListRolesRequest)(nil),           // 6: auth.v1.ListRolesRequest
	(*ListRolesResponse)(nil),          // 7: auth.v1.ListRolesResponse
	(*DeleteRoleRequest)(nil),          // 8: auth.v1.DeleteRoleRequest
	(*CreatePermissionRequest)(nil),    // 9: auth.v1.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),   // 10: auth.v1.CreatePermissionResponse
	(*UpdatePermissionRequest)(nil),    // 11: auth.v1.UpdatePermissionRequest
	(*GetPermissionRequest)(nil),       // 12: auth.v1.GetPermissionRequest
	(*ListPermissionsRequest)(nil),     // 13: auth.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),    // 14: auth.v1.ListPermissionsResponse
	(*DeletePermissionRequest)(nil),    // 15: auth.v1.DeletePermissionRequest
	(*CheckPermissionsRequest)(nil),    // 16: auth.v1.CheckPermissionsRequest
	(*CheckPermissionsResponse)(nil),   // 17: auth.v1.CheckPermissionsResponse
	(*HasPermissionRequest)(nil),       // 18: auth.v1.HasPermissionRequest
	(*HasPermissionResponse)(nil),      // 19: auth.v1.HasPermissionResponse
	(*GetUserPermissionsRequest)(nil),  // 20: auth.v1.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil), // 21: auth.v1.GetUserPermissionsResponse
	(*GetUserRolesRequest)(nil),        // 22: auth.v1.GetUserRolesRequest
	(*GetUserRolesResponse)(nil),       // 23: auth.v1.GetUserRolesResponse
	(*IsSystemTenantUserRequest)(nil),  // 24: auth.v1.IsSystemTenantUserRequest
	(*IsSystemTenantUserResponse)(nil), // 25: auth.v1.IsSystemTenantUserResponse
	nil,                                // 26: auth.v1.CheckPermissionsResponse.PermissionsEntry
	nil,                                // 27: auth.v1.GetUserPermissionsResponse.PermissionsEntry
	(*v1.UserIdentifier)(nil),          // 28: infra.v1.UserIdentifier
	(*Role)(nil),                       // 29: auth.v1.Role
	(*v1.PaginationRequest)(nil),       // 30: infra.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),      // 31: infra.v1.PaginationResponse
	(*Permission)(nil),                 // 32: auth.v1.Permission
	(*v1.Response)(nil),                // 33: infra.v1.Response
}
var file_auth_v1_rbac_proto_depIdxs = []int32{
	28, // 0: auth.v1.AssignRolesRequest.identifier:type_name -> infra.v1.UserIdentifier
	28, // 1: auth.v1.RemoveRolesRequest.identifier:type_name -> infra.v1.UserIdentifier
	28, // 2: auth.v1.CreateRoleRequest.identifier:type_name -> infra.v1.UserIdentifier
	29, // 3: auth.v1.CreateRoleRequest.role:type_name -> auth.v1.Role
	28, // 4: auth.v1.UpdateRoleRequest.identifier:type_name -> infra.v1.UserIdentifier
	29, // 5: auth.v1.UpdateRoleRequest.role:type_name -> auth.v1.Role
	28, // 6: auth.v1.GetRoleRequest.identifier:type_name -> infra.v1.UserIdentifier
	28, // 7: auth.v1.ListRolesRequest.identifier:type_name -> infra.v1.UserIdentifier
	30, // 8: auth.v1.ListRolesRequest.pagination:type_name -> infra.v1.PaginationRequest
	29, // 9: auth.v1.ListRolesResponse.roles:type_name -> auth.v1.Role
	31, // 10: auth.v1.ListRolesResponse.pagination:type_name -> infra.v1.PaginationResponse
	28, // 11: auth.v1.DeleteRoleRequest.identifier:type_name -> infra.v1.UserIdentifier
	28, // 12: auth.v1.CreatePermissionRequest.identifier:type_name -> infra.v1.UserIdentifier
	32, // 13: auth.v1.CreatePermissionRequest.permission:type_name -> auth.v1.Permission
	28, // 14: auth.v1.UpdatePermissionRequest.identifier:type_name -> infra.v1.UserIdentifier
	32, // 15: auth.v1.UpdatePermissionRequest.permission:type_name -> auth.v1.Permission
	28, // 16: auth.v1.GetPermissionRequest.identifier:type_name -> infra.v1.UserIdentifier
	28, // 17: auth.v1.ListPermissionsRequest.identifier:type_name -> infra.v1.UserIdentifier
	30, // 18: auth.v1.ListPermissionsRequest.pagination:type_name -> infra.v1.PaginationRequest
	32, // 19: auth.v1.ListPermissionsResponse.permissions:type_name -> auth.v1.Permission
	31, // 20: auth.v1.ListPermissionsResponse.pagination:type_name -> infra.v1.PaginationResponse
	28, // 21: auth.v1.DeletePermissionRequest.identifier:type_name -> infra.v1.UserIdentifier
	28, // 22: auth.v1.CheckPermissionsRequest.identifier:type_name -> infra.v1.UserIdentifier
	26, // 23: auth.v1.CheckPermissionsResponse.permissions:type_name -> auth.v1.CheckPermissionsResponse.PermissionsEntry
	28, // 24: auth.v1.HasPermissionRequest.identifier:type_name -> infra.v1.UserIdentifier
	28, // 25: auth.v1.GetUserPermissionsRequest.identifier:type_name -> infra.v1.UserIdentifier
	27, // 26: auth.v1.GetUserPermissionsResponse.permissions:type_name -> auth.v1.GetUserPermissionsResponse.PermissionsEntry
	28, // 27: auth.v1.GetUserRolesRequest.identifier:type_name -> infra.v1.UserIdentifier
	2,  // 28: auth.v1.RoleService.CreateRole:input_type -> auth.v1.CreateRoleRequest
	4,  // 29: auth.v1.RoleService.UpdateRole:input_type -> auth.v1.UpdateRoleRequest
	5,  // 30: auth.v1.RoleService.GetRole:input_type -> auth.v1.GetRoleRequest
	6,  // 31: auth.v1.RoleService.ListRoles:input_type -> auth.v1.ListRolesRequest
	8,  // 32: auth.v1.RoleService.DeleteRole:input_type -> auth.v1.DeleteRoleRequest
	9,  // 33: auth.v1.PermissionService.CreatePermission:input_type -> auth.v1.CreatePermissionRequest
	11, // 34: auth.v1.PermissionService.UpdatePermission:input_type -> auth.v1.UpdatePermissionRequest
	12, // 35: auth.v1.PermissionService.GetPermission:input_type -> auth.v1.GetPermissionRequest
	13, // 36: auth.v1.PermissionService.ListPermissions:input_type -> auth.v1.ListPermissionsRequest
	15, // 37: auth.v1.PermissionService.DeletePermission:input_type -> auth.v1.DeletePermissionRequest
	16, // 38: auth.v1.VerificationService.CheckPermissions:input_type -> auth.v1.CheckPermissionsRequest
	18, // 39: auth.v1.VerificationService.HasPermission:input_type -> auth.v1.HasPermissionRequest
	20, // 40: auth.v1.VerificationService.GetUserPermissions:input_type -> auth.v1.GetUserPermissionsRequest
	22, // 41: auth.v1.VerificationService.GetUserRoles:input_type -> auth.v1.GetUserRolesRequest
	24, // 42: auth.v1.VerificationService.IsSystemTenantUser:input_type -> auth.v1.IsSystemTenantUserRequest
	3,  // 43: auth.v1.RoleService.CreateRole:output_type -> auth.v1.CreateRoleResponse
	33, // 44: auth.v1.RoleService.UpdateRole:output_type -> infra.v1.Response
	29, // 45: auth.v1.RoleService.GetRole:output_type -> auth.v1.Role
	7,  // 46: auth.v1.RoleService.ListRoles:output_type -> auth.v1.ListRolesResponse
	33, // 47: auth.v1.RoleService.DeleteRole:output_type -> infra.v1.Response
	10, // 48: auth.v1.PermissionService.CreatePermission:output_type -> auth.v1.CreatePermissionResponse
	33, // 49: auth.v1.PermissionService.UpdatePermission:output_type -> infra.v1.Response
	32, // 50: auth.v1.PermissionService.GetPermission:output_type -> auth.v1.Permission
	14, // 51: auth.v1.PermissionService.ListPermissions:output_type -> auth.v1.ListPermissionsResponse
	33, // 52: auth.v1.PermissionService.DeletePermission:output_type -> infra.v1.Response
	17, // 53: auth.v1.VerificationService.CheckPermissions:output_type -> auth.v1.CheckPermissionsResponse
	19, // 54: auth.v1.VerificationService.HasPermission:output_type -> auth.v1.HasPermissionResponse
	21, // 55: auth.v1.VerificationService.GetUserPermissions:output_type -> auth.v1.GetUserPermissionsResponse
	23, // 56: auth.v1.VerificationService.GetUserRoles:output_type -> auth.v1.GetUserRolesResponse
	25, // 57: auth.v1.VerificationService.IsSystemTenantUser:output_type -> auth.v1.IsSystemTenantUserResponse
	43, // [43:58] is the sub-list for method output_type
	28, // [28:43] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_auth_v1_rbac_proto_init() }
func file_auth_v1_rbac_proto_init() {
	if File_auth_v1_rbac_proto != nil {
		return
	}
	file_auth_v1_role_proto_init()
	file_auth_v1_permission_proto_init()
	file_auth_v1_rbac_proto_msgTypes[6].OneofWrappers = []any{}
	file_auth_v1_rbac_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_rbac_proto_rawDesc), len(file_auth_v1_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_auth_v1_rbac_proto_goTypes,
		DependencyIndexes: file_auth_v1_rbac_proto_depIdxs,
		MessageInfos:      file_auth_v1_rbac_proto_msgTypes,
	}.Build()
	File_auth_v1_rbac_proto = out.File
	file_auth_v1_rbac_proto_goTypes = nil
	file_auth_v1_rbac_proto_depIdxs = nil
}
