// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth/v1/user_group.proto

package authv1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserGroup model for MongoDB auth_db.user_groups collection
type UserGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id" bson:"tenant_id"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name" bson:"name"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description" bson:"description"`
	Members       []*GroupMember         `protobuf:"bytes,5,rep,name=members,proto3" json:"members" bson:"members"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles" bson:"roles"`
	Permissions   []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty" bson:"permissions,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status" bson:"status"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at" bson:"created_at"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at" bson:"updated_at"`
	CreatedBy     string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by" bson:"created_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroup) Reset() {
	*x = UserGroup{}
	mi := &file_auth_v1_user_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroup) ProtoMessage() {}

func (x *UserGroup) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroup.ProtoReflect.Descriptor instead.
func (*UserGroup) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_group_proto_rawDescGZIP(), []int{0}
}

func (x *UserGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserGroup) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserGroup) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *UserGroup) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserGroup) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UserGroup) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserGroup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserGroup) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserGroup) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id" bson:"user_id"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at" bson:"joined_at"`
	AddedBy       string                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by" bson:"added_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_auth_v1_user_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *GroupMember) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

var File_auth_v1_user_group_proto protoreflect.FileDescriptor

const file_auth_v1_user_group_proto_rawDesc = "" +
	"\n" +
	"\x18auth/v1/user_group.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\xbe\x06\n" +
	"\tUserGroup\x123\n" +
	"\x02id\x18\x01 \x01(\tB#\x9a\x84\x9e\x03\x1ebson:\"_id,omitempty\" json:\"id\"R\x02id\x12C\n" +
	"\ttenant_id\x18\x02 \x01(\tB&\x9a\x84\x9e\x03!bson:\"tenant_id\" json:\"tenant_id\"R\btenantId\x120\n" +
	"\x04name\x18\x03 \x01(\tB\x1c\x9a\x84\x9e\x03\x17bson:\"name\" json:\"name\"R\x04name\x12L\n" +
	"\vdescription\x18\x04 \x01(\tB*\x9a\x84\x9e\x03%bson:\"description\" json:\"description\"R\vdescription\x12R\n" +
	"\amembers\x18\x05 \x03(\v2\x14.auth.v1.GroupMemberB\"\x9a\x84\x9e\x03\x1dbson:\"members\" json:\"members\"R\amembers\x124\n" +
	"\x05roles\x18\x06 \x03(\tB\x1e\x9a\x84\x9e\x03\x19bson:\"roles\" json:\"roles\"R\x05roles\x12`\n" +
	"\vpermissions\x18\a \x03(\tB>\x9a\x84\x9e\x039bson:\"permissions,omitempty\" json:\"permissions,omitempty\"R\vpermissions\x128\n" +
	"\x06status\x18\b \x01(\tB \x9a\x84\x9e\x03\x1bbson:\"status\" json:\"status\"R\x06status\x12c\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB(\x9a\x84\x9e\x03#bson:\"created_at\" json:\"created_at\"R\tcreatedAt\x12c\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB(\x9a\x84\x9e\x03#bson:\"updated_at\" json:\"updated_at\"R\tupdatedAt\x12G\n" +
	"\n" +
	"created_by\x18\v \x01(\tB(\x9a\x84\x9e\x03#bson:\"created_by\" json:\"created_by\"R\tcreatedBy\"\xec\x01\n" +
	"\vGroupMember\x12;\n" +
	"\auser_id\x18\x01 \x01(\tB\"\x9a\x84\x9e\x03\x1dbson:\"user_id\" json:\"user_id\"R\x06userId\x12_\n" +
	"\tjoined_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB&\x9a\x84\x9e\x03!bson:\"joined_at\" json:\"joined_at\"R\bjoinedAt\x12?\n" +
	"\badded_by\x18\x03 \x01(\tB$\x9a\x84\x9e\x03\x1fbson:\"added_by\" json:\"added_by\"R\aaddedByB3Z1erp.localhost/internal/infra/model/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_user_group_proto_rawDescOnce sync.Once
	file_auth_v1_user_group_proto_rawDescData []byte
)

func file_auth_v1_user_group_proto_rawDescGZIP() []byte {
	file_auth_v1_user_group_proto_rawDescOnce.Do(func() {
		file_auth_v1_user_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_user_group_proto_rawDesc), len(file_auth_v1_user_group_proto_rawDesc)))
	})
	return file_auth_v1_user_group_proto_rawDescData
}

var file_auth_v1_user_group_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_v1_user_group_proto_goTypes = []any{
	(*UserGroup)(nil),             // 0: auth.v1.UserGroup
	(*GroupMember)(nil),           // 1: auth.v1.GroupMember
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_auth_v1_user_group_proto_depIdxs = []int32{
	1, // 0: auth.v1.UserGroup.members:type_name -> auth.v1.GroupMember
	2, // 1: auth.v1.UserGroup.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: auth.v1.UserGroup.updated_at:type_name -> google.protobuf.Timestamp
	2, // 3: auth.v1.GroupMember.joined_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_auth_v1_user_group_proto_init() }
func file_auth_v1_user_group_proto_init() {
	if File_auth_v1_user_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_user_group_proto_rawDesc), len(file_auth_v1_user_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_user_group_proto_goTypes,
		DependencyIndexes: file_auth_v1_user_group_proto_depIdxs,
		MessageInfos:      file_auth_v1_user_group_proto_msgTypes,
	}.Build()
	File_auth_v1_user_group_proto = out.File
	file_auth_v1_user_group_proto_goTypes = nil
	file_auth_v1_user_group_proto_depIdxs = nil
}
