// Code generated by MockGen. DO NOT EDIT.
// Source: erp.localhost/internal/auth/handler (interfaces: TokenHandler)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_token_handler.go -package=mock erp.localhost/internal/auth/handler TokenHandler
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenHandler is a mock of TokenHandler interface.
type MockTokenHandler[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockTokenHandlerMockRecorder[T]
	isgomock struct{}
}

// MockTokenHandlerMockRecorder is the mock recorder for MockTokenHandler.
type MockTokenHandlerMockRecorder[T any] struct {
	mock *MockTokenHandler[T]
}

// NewMockTokenHandler creates a new mock instance.
func NewMockTokenHandler[T any](ctrl *gomock.Controller) *MockTokenHandler[T] {
	mock := &MockTokenHandler[T]{ctrl: ctrl}
	mock.recorder = &MockTokenHandlerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenHandler[T]) EXPECT() *MockTokenHandlerMockRecorder[T] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTokenHandler[T]) Delete(tenantID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tenantID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTokenHandlerMockRecorder[T]) Delete(tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTokenHandler[T])(nil).Delete), tenantID, userID)
}

// DeleteByPattern mocks base method.
func (m *MockTokenHandler[T]) DeleteByPattern(tenantID, pattern string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPattern", tenantID, pattern)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByPattern indicates an expected call of DeleteByPattern.
func (mr *MockTokenHandlerMockRecorder[T]) DeleteByPattern(tenantID, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPattern", reflect.TypeOf((*MockTokenHandler[T])(nil).DeleteByPattern), tenantID, pattern)
}

// GetOne mocks base method.
func (m *MockTokenHandler[T]) GetOne(tenantID, userID string) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", tenantID, userID)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockTokenHandlerMockRecorder[T]) GetOne(tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockTokenHandler[T])(nil).GetOne), tenantID, userID)
}

// Revoke mocks base method.
func (m *MockTokenHandler[T]) Revoke(tenantID, userID, revokedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", tenantID, userID, revokedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenHandlerMockRecorder[T]) Revoke(tenantID, userID, revokedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenHandler[T])(nil).Revoke), tenantID, userID, revokedBy)
}

// ScanKeys mocks base method.
func (m *MockTokenHandler[T]) ScanKeys(tenantID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanKeys", tenantID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanKeys indicates an expected call of ScanKeys.
func (mr *MockTokenHandlerMockRecorder[T]) ScanKeys(tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanKeys", reflect.TypeOf((*MockTokenHandler[T])(nil).ScanKeys), tenantID)
}

// Store mocks base method.
func (m *MockTokenHandler[T]) Store(tenantID, userID string, value *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", tenantID, userID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTokenHandlerMockRecorder[T]) Store(tenantID, userID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTokenHandler[T])(nil).Store), tenantID, userID, value)
}

// Validate mocks base method.
func (m *MockTokenHandler[T]) Validate(tenantID, userID string) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", tenantID, userID)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockTokenHandlerMockRecorder[T]) Validate(tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTokenHandler[T])(nil).Validate), tenantID, userID)
}
