# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/token_claims.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'auth/v1/token_claims.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from tagger import tagger_pb2 as tagger_dot_tagger__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61uth/v1/token_claims.proto\x12\x07\x61uth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\x8b\x04\n\x11\x41\x63\x63\x65ssTokenClaims\x12\x33\n\x07user_id\x18\x01 \x01(\tB\"\x9a\x84\x9e\x03\x1d\x62son:\"user_id\" json:\"user_id\"\x12\x39\n\ttenant_id\x18\x02 \x01(\tB&\x9a\x84\x9e\x03!bson:\"tenant_id\" json:\"tenant_id\"\x12\x36\n\x08username\x18\x03 \x01(\tB$\x9a\x84\x9e\x03\x1f\x62son:\"username\" json:\"username\"\x12-\n\x05\x65mail\x18\x04 \x01(\tB\x1e\x9a\x84\x9e\x03\x19\x62son:\"email\" json:\"email\"\x12-\n\x05roles\x18\x05 \x03(\tB\x1e\x9a\x84\x9e\x03\x19\x62son:\"roles\" json:\"roles\"\x12?\n\x0bpermissions\x18\x06 \x03(\tB*\x9a\x84\x9e\x03%bson:\"permissions\" json:\"permissions\"\x12U\n\tissued_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB&\x9a\x84\x9e\x03!bson:\"issued_at\" json:\"issued_at\"\x12X\n\nexpires_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampB(\x9a\x84\x9e\x03#bson:\"expires_at\" json:\"expires_at\"B*Z(erp.localhost/infra/model/auth/v1;authv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.token_claims_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(erp.localhost/infra/model/auth/v1;authv1'
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['user_id']._loaded_options = None
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['user_id']._serialized_options = b'\232\204\236\003\035bson:\"user_id\" json:\"user_id\"'
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['tenant_id']._loaded_options = None
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['tenant_id']._serialized_options = b'\232\204\236\003!bson:\"tenant_id\" json:\"tenant_id\"'
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['username']._loaded_options = None
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['username']._serialized_options = b'\232\204\236\003\037bson:\"username\" json:\"username\"'
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['email']._loaded_options = None
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['email']._serialized_options = b'\232\204\236\003\031bson:\"email\" json:\"email\"'
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['roles']._loaded_options = None
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['roles']._serialized_options = b'\232\204\236\003\031bson:\"roles\" json:\"roles\"'
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['permissions']._loaded_options = None
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['permissions']._serialized_options = b'\232\204\236\003%bson:\"permissions\" json:\"permissions\"'
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['issued_at']._loaded_options = None
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['issued_at']._serialized_options = b'\232\204\236\003!bson:\"issued_at\" json:\"issued_at\"'
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['expires_at']._loaded_options = None
  _globals['_ACCESSTOKENCLAIMS'].fields_by_name['expires_at']._serialized_options = b'\232\204\236\003#bson:\"expires_at\" json:\"expires_at\"'
  _globals['_ACCESSTOKENCLAIMS']._serialized_start=94
  _globals['_ACCESSTOKENCLAIMS']._serialized_end=617
# @@protoc_insertion_point(module_scope)
