// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/v1/feature_flag.proto

package configv1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeatureFlag represents a feature flag
// Stored in MongoDB config_db.feature_flags collection
type FeatureFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id,omitempty"`
	FlagId        string                 `protobuf:"bytes,2,opt,name=flag_id,json=flagId,proto3" json:"flag_id" bson:"flag_id"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name" bson:"name"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key" bson:"key"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description" bson:"description"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled" bson:"enabled"`
	Rollout       *FeatureRollout        `protobuf:"bytes,7,opt,name=rollout,proto3" json:"rollout" bson:"rollout"`
	Metadata      *FeatureFlagMetadata   `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty" bson:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at" bson:"created_at"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at" bson:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureFlag) Reset() {
	*x = FeatureFlag{}
	mi := &file_config_v1_feature_flag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlag) ProtoMessage() {}

func (x *FeatureFlag) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_feature_flag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureFlag.ProtoReflect.Descriptor instead.
func (*FeatureFlag) Descriptor() ([]byte, []int) {
	return file_config_v1_feature_flag_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureFlag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeatureFlag) GetFlagId() string {
	if x != nil {
		return x.FlagId
	}
	return ""
}

func (x *FeatureFlag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeatureFlag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FeatureFlag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeatureFlag) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FeatureFlag) GetRollout() *FeatureRollout {
	if x != nil {
		return x.Rollout
	}
	return nil
}

func (x *FeatureFlag) GetMetadata() *FeatureFlagMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FeatureFlag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FeatureFlag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FeatureRollout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    int32                  `protobuf:"varint,1,opt,name=percentage,proto3" json:"percentage" bson:"percentage"`
	TenantIds     []string               `protobuf:"bytes,2,rep,name=tenant_ids,json=tenantIds,proto3" json:"tenant_ids,omitempty" bson:"tenant_ids,omitempty"`
	UserIds       []string               `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty" bson:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureRollout) Reset() {
	*x = FeatureRollout{}
	mi := &file_config_v1_feature_flag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureRollout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureRollout) ProtoMessage() {}

func (x *FeatureRollout) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_feature_flag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureRollout.ProtoReflect.Descriptor instead.
func (*FeatureRollout) Descriptor() ([]byte, []int) {
	return file_config_v1_feature_flag_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureRollout) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *FeatureRollout) GetTenantIds() []string {
	if x != nil {
		return x.TenantIds
	}
	return nil
}

func (x *FeatureRollout) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type FeatureFlagMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Category         string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty" bson:"category,omitempty"`
	OwnerTeam        string                 `protobuf:"bytes,2,opt,name=owner_team,json=ownerTeam,proto3" json:"owner_team,omitempty" bson:"owner_team,omitempty"`
	DocumentationUrl string                 `protobuf:"bytes,3,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty" bson:"documentation_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeatureFlagMetadata) Reset() {
	*x = FeatureFlagMetadata{}
	mi := &file_config_v1_feature_flag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureFlagMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlagMetadata) ProtoMessage() {}

func (x *FeatureFlagMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_feature_flag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureFlagMetadata.ProtoReflect.Descriptor instead.
func (*FeatureFlagMetadata) Descriptor() ([]byte, []int) {
	return file_config_v1_feature_flag_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureFlagMetadata) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FeatureFlagMetadata) GetOwnerTeam() string {
	if x != nil {
		return x.OwnerTeam
	}
	return ""
}

func (x *FeatureFlagMetadata) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

var File_config_v1_feature_flag_proto protoreflect.FileDescriptor

const file_config_v1_feature_flag_proto_rawDesc = "" +
	"\n" +
	"\x1cconfig/v1/feature_flag.proto\x12\tconfig.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\x84\x06\n" +
	"\vFeatureFlag\x123\n" +
	"\x02id\x18\x01 \x01(\tB#\x9a\x84\x9e\x03\x1ebson:\"_id,omitempty\" json:\"id\"R\x02id\x12;\n" +
	"\aflag_id\x18\x02 \x01(\tB\"\x9a\x84\x9e\x03\x1dbson:\"flag_id\" json:\"flag_id\"R\x06flagId\x120\n" +
	"\x04name\x18\x03 \x01(\tB\x1c\x9a\x84\x9e\x03\x17bson:\"name\" json:\"name\"R\x04name\x12,\n" +
	"\x03key\x18\x04 \x01(\tB\x1a\x9a\x84\x9e\x03\x15bson:\"key\" json:\"key\"R\x03key\x12L\n" +
	"\vdescription\x18\x05 \x01(\tB*\x9a\x84\x9e\x03%bson:\"description\" json:\"description\"R\vdescription\x12<\n" +
	"\aenabled\x18\x06 \x01(\bB\"\x9a\x84\x9e\x03\x1dbson:\"enabled\" json:\"enabled\"R\aenabled\x12W\n" +
	"\arollout\x18\a \x01(\v2\x19.config.v1.FeatureRolloutB\"\x9a\x84\x9e\x03\x1dbson:\"rollout\" json:\"rollout\"R\arollout\x12t\n" +
	"\bmetadata\x18\b \x01(\v2\x1e.config.v1.FeatureFlagMetadataB8\x9a\x84\x9e\x033bson:\"metadata,omitempty\" json:\"metadata,omitempty\"R\bmetadata\x12c\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB(\x9a\x84\x9e\x03#bson:\"created_at\" json:\"created_at\"R\tcreatedAt\x12c\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB(\x9a\x84\x9e\x03#bson:\"updated_at\" json:\"updated_at\"R\tupdatedAt\"\x8c\x02\n" +
	"\x0eFeatureRollout\x12H\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x05B(\x9a\x84\x9e\x03#bson:\"percentage\" json:\"percentage\"R\n" +
	"percentage\x12[\n" +
	"\n" +
	"tenant_ids\x18\x02 \x03(\tB<\x9a\x84\x9e\x037bson:\"tenant_ids,omitempty\" json:\"tenant_ids,omitempty\"R\ttenantIds\x12S\n" +
	"\buser_ids\x18\x03 \x03(\tB8\x9a\x84\x9e\x033bson:\"user_ids,omitempty\" json:\"user_ids,omitempty\"R\auserIds\"\xc1\x02\n" +
	"\x13FeatureFlagMetadata\x12T\n" +
	"\bcategory\x18\x01 \x01(\tB8\x9a\x84\x9e\x033bson:\"category,omitempty\" json:\"category,omitempty\"R\bcategory\x12[\n" +
	"\n" +
	"owner_team\x18\x02 \x01(\tB<\x9a\x84\x9e\x037bson:\"owner_team,omitempty\" json:\"owner_team,omitempty\"R\townerTeam\x12w\n" +
	"\x11documentation_url\x18\x03 \x01(\tBJ\x9a\x84\x9e\x03Ebson:\"documentation_url,omitempty\" json:\"documentation_url,omitempty\"R\x10documentationUrlB7Z5erp.localhost/internal/infra/model/config/v1;configv1b\x06proto3"

var (
	file_config_v1_feature_flag_proto_rawDescOnce sync.Once
	file_config_v1_feature_flag_proto_rawDescData []byte
)

func file_config_v1_feature_flag_proto_rawDescGZIP() []byte {
	file_config_v1_feature_flag_proto_rawDescOnce.Do(func() {
		file_config_v1_feature_flag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_feature_flag_proto_rawDesc), len(file_config_v1_feature_flag_proto_rawDesc)))
	})
	return file_config_v1_feature_flag_proto_rawDescData
}

var file_config_v1_feature_flag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_config_v1_feature_flag_proto_goTypes = []any{
	(*FeatureFlag)(nil),           // 0: config.v1.FeatureFlag
	(*FeatureRollout)(nil),        // 1: config.v1.FeatureRollout
	(*FeatureFlagMetadata)(nil),   // 2: config.v1.FeatureFlagMetadata
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_config_v1_feature_flag_proto_depIdxs = []int32{
	1, // 0: config.v1.FeatureFlag.rollout:type_name -> config.v1.FeatureRollout
	2, // 1: config.v1.FeatureFlag.metadata:type_name -> config.v1.FeatureFlagMetadata
	3, // 2: config.v1.FeatureFlag.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: config.v1.FeatureFlag.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_config_v1_feature_flag_proto_init() }
func file_config_v1_feature_flag_proto_init() {
	if File_config_v1_feature_flag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_feature_flag_proto_rawDesc), len(file_config_v1_feature_flag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_feature_flag_proto_goTypes,
		DependencyIndexes: file_config_v1_feature_flag_proto_depIdxs,
		MessageInfos:      file_config_v1_feature_flag_proto_msgTypes,
	}.Build()
	File_config_v1_feature_flag_proto = out.File
	file_config_v1_feature_flag_proto_goTypes = nil
	file_config_v1_feature_flag_proto_depIdxs = nil
}
