// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuth) Reset() {
	*x = UserAuth{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuth) ProtoMessage() {}

func (x *UserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuth.ProtoReflect.Descriptor instead.
func (*UserAuth) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserAuth) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserAuth) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentifier) Reset() {
	*x = UserIdentifier{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentifier) ProtoMessage() {}

func (x *UserIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentifier.ProtoReflect.Descriptor instead.
func (*UserIdentifier) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UserIdentifier) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserIdentifier) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Tokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tokens) Reset() {
	*x = Tokens{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokens) ProtoMessage() {}

func (x *Tokens) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokens.ProtoReflect.Descriptor instead.
func (*Tokens) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Tokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Tokens) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ExpiresIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   int64                  `protobuf:"varint,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  int64                  `protobuf:"varint,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpiresIn) Reset() {
	*x = ExpiresIn{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpiresIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpiresIn) ProtoMessage() {}

func (x *ExpiresIn) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpiresIn.ProtoReflect.Descriptor instead.
func (*ExpiresIn) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ExpiresIn) GetAccessToken() int64 {
	if x != nil {
		return x.AccessToken
	}
	return 0
}

func (x *ExpiresIn) GetRefreshToken() int64 {
	if x != nil {
		return x.RefreshToken
	}
	return 0
}

type PermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    string                 `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	HasPermission bool                   `protobuf:"varint,2,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResponse) Reset() {
	*x = PermissionResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResponse) ProtoMessage() {}

func (x *PermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResponse.ProtoReflect.Descriptor instead.
func (*PermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionResponse) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *PermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserAuth              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticateRequest) GetUser() *UserAuth {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserIdentifier        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Tokens        *Tokens                `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	ExpiresIn     *ExpiresIn             `protobuf:"bytes,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AuthenticateResponse) GetUser() *UserIdentifier {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthenticateResponse) GetTokens() *Tokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *AuthenticateResponse) GetExpiresIn() *ExpiresIn {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserIdentifier        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenRequest) GetUser() *UserIdentifier {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserIdentifier        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Tokens        *Tokens                `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	ExpiresIn     *ExpiresIn             `protobuf:"bytes,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenResponse) GetUser() *UserIdentifier {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RefreshTokenResponse) GetTokens() *Tokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *RefreshTokenResponse) GetExpiresIn() *ExpiresIn {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserIdentifier        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Tokens        *Tokens                `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	RequestBy     string                 `protobuf:"bytes,3,opt,name=request_by,json=requestBy,proto3" json:"request_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeTokenRequest) GetUser() *UserIdentifier {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RevokeTokenRequest) GetTokens() *Tokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *RevokeTokenRequest) GetRequestBy() string {
	if x != nil {
		return x.RequestBy
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserIdentifier        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Revoked       bool                   `protobuf:"varint,2,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeTokenResponse) GetUser() *UserIdentifier {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RevokeTokenResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *Tokens                `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *LogoutRequest) GetTokens() *Tokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserIdentifier        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *LogoutResponse) GetUser() *UserIdentifier {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserIdentifier        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsRequest) Reset() {
	*x = CheckPermissionsRequest{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsRequest) ProtoMessage() {}

func (x *CheckPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *CheckPermissionsRequest) GetUser() *UserIdentifier {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CheckPermissionsRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CheckPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserIdentifier        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Permissions   []*PermissionResponse  `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsResponse) Reset() {
	*x = CheckPermissionsResponse{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsResponse) ProtoMessage() {}

func (x *CheckPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

func (x *CheckPermissionsResponse) GetUser() *UserIdentifier {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CheckPermissionsResponse) GetPermissions() []*PermissionResponse {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\aauth.v1\"Y\n" +
	"\bUserAuth\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"F\n" +
	"\x0eUserIdentifier\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x06Tokens\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"S\n" +
	"\tExpiresIn\x12!\n" +
	"\faccess_token\x18\x01 \x01(\x03R\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\x03R\frefreshToken\"[\n" +
	"\x12PermissionResponse\x12\x1e\n" +
	"\n" +
	"permission\x18\x01 \x01(\tR\n" +
	"permission\x12%\n" +
	"\x0ehas_permission\x18\x02 \x01(\bR\rhasPermission\"X\n" +
	"\x13AuthenticateRequest\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.auth.v1.UserAuthR\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9f\x01\n" +
	"\x14AuthenticateResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.auth.v1.UserIdentifierR\x04user\x12'\n" +
	"\x06tokens\x18\x02 \x01(\v2\x0f.auth.v1.TokensR\x06tokens\x121\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\v2\x12.auth.v1.ExpiresInR\texpiresIn\"7\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"+\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"g\n" +
	"\x13RefreshTokenRequest\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.auth.v1.UserIdentifierR\x04user\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\x9f\x01\n" +
	"\x14RefreshTokenResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.auth.v1.UserIdentifierR\x04user\x12'\n" +
	"\x06tokens\x18\x02 \x01(\v2\x0f.auth.v1.TokensR\x06tokens\x121\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\v2\x12.auth.v1.ExpiresInR\texpiresIn\"\x89\x01\n" +
	"\x12RevokeTokenRequest\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.auth.v1.UserIdentifierR\x04user\x12'\n" +
	"\x06tokens\x18\x02 \x01(\v2\x0f.auth.v1.TokensR\x06tokens\x12\x1d\n" +
	"\n" +
	"request_by\x18\x03 \x01(\tR\trequestBy\"\\\n" +
	"\x13RevokeTokenResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.auth.v1.UserIdentifierR\x04user\x12\x18\n" +
	"\arevoked\x18\x02 \x01(\bR\arevoked\"8\n" +
	"\rLogoutRequest\x12'\n" +
	"\x06tokens\x18\x01 \x01(\v2\x0f.auth.v1.TokensR\x06tokens\"W\n" +
	"\x0eLogoutResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.auth.v1.UserIdentifierR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\x17CheckPermissionsRequest\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.auth.v1.UserIdentifierR\x04user\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\x86\x01\n" +
	"\x18CheckPermissionsResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.auth.v1.UserIdentifierR\x04user\x12=\n" +
	"\vpermissions\x18\x02 \x03(\v2\x1b.auth.v1.PermissionResponseR\vpermissions2\xcf\x03\n" +
	"\vAuthService\x12K\n" +
	"\fAuthenticate\x12\x1c.auth.v1.AuthenticateRequest\x1a\x1d.auth.v1.AuthenticateResponse\x12H\n" +
	"\vVerifyToken\x12\x1b.auth.v1.VerifyTokenRequest\x1a\x1c.auth.v1.VerifyTokenResponse\x12K\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x1d.auth.v1.RefreshTokenResponse\x12H\n" +
	"\vRevokeToken\x12\x1b.auth.v1.RevokeTokenRequest\x1a\x1c.auth.v1.RevokeTokenResponse\x129\n" +
	"\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x17.auth.v1.LogoutResponse\x12W\n" +
	"\x10CheckPermissions\x12 .auth.v1.CheckPermissionsRequest\x1a!.auth.v1.CheckPermissionsResponseB2Z0erp.localhost/internal/auth/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_auth_proto_goTypes = []any{
	(*UserAuth)(nil),                 // 0: auth.v1.UserAuth
	(*UserIdentifier)(nil),           // 1: auth.v1.UserIdentifier
	(*Tokens)(nil),                   // 2: auth.v1.Tokens
	(*ExpiresIn)(nil),                // 3: auth.v1.ExpiresIn
	(*PermissionResponse)(nil),       // 4: auth.v1.PermissionResponse
	(*AuthenticateRequest)(nil),      // 5: auth.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),     // 6: auth.v1.AuthenticateResponse
	(*VerifyTokenRequest)(nil),       // 7: auth.v1.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),      // 8: auth.v1.VerifyTokenResponse
	(*RefreshTokenRequest)(nil),      // 9: auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),     // 10: auth.v1.RefreshTokenResponse
	(*RevokeTokenRequest)(nil),       // 11: auth.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),      // 12: auth.v1.RevokeTokenResponse
	(*LogoutRequest)(nil),            // 13: auth.v1.LogoutRequest
	(*LogoutResponse)(nil),           // 14: auth.v1.LogoutResponse
	(*CheckPermissionsRequest)(nil),  // 15: auth.v1.CheckPermissionsRequest
	(*CheckPermissionsResponse)(nil), // 16: auth.v1.CheckPermissionsResponse
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: auth.v1.AuthenticateRequest.user:type_name -> auth.v1.UserAuth
	1,  // 1: auth.v1.AuthenticateResponse.user:type_name -> auth.v1.UserIdentifier
	2,  // 2: auth.v1.AuthenticateResponse.tokens:type_name -> auth.v1.Tokens
	3,  // 3: auth.v1.AuthenticateResponse.expires_in:type_name -> auth.v1.ExpiresIn
	1,  // 4: auth.v1.RefreshTokenRequest.user:type_name -> auth.v1.UserIdentifier
	1,  // 5: auth.v1.RefreshTokenResponse.user:type_name -> auth.v1.UserIdentifier
	2,  // 6: auth.v1.RefreshTokenResponse.tokens:type_name -> auth.v1.Tokens
	3,  // 7: auth.v1.RefreshTokenResponse.expires_in:type_name -> auth.v1.ExpiresIn
	1,  // 8: auth.v1.RevokeTokenRequest.user:type_name -> auth.v1.UserIdentifier
	2,  // 9: auth.v1.RevokeTokenRequest.tokens:type_name -> auth.v1.Tokens
	1,  // 10: auth.v1.RevokeTokenResponse.user:type_name -> auth.v1.UserIdentifier
	2,  // 11: auth.v1.LogoutRequest.tokens:type_name -> auth.v1.Tokens
	1,  // 12: auth.v1.LogoutResponse.user:type_name -> auth.v1.UserIdentifier
	1,  // 13: auth.v1.CheckPermissionsRequest.user:type_name -> auth.v1.UserIdentifier
	1,  // 14: auth.v1.CheckPermissionsResponse.user:type_name -> auth.v1.UserIdentifier
	4,  // 15: auth.v1.CheckPermissionsResponse.permissions:type_name -> auth.v1.PermissionResponse
	5,  // 16: auth.v1.AuthService.Authenticate:input_type -> auth.v1.AuthenticateRequest
	7,  // 17: auth.v1.AuthService.VerifyToken:input_type -> auth.v1.VerifyTokenRequest
	9,  // 18: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	11, // 19: auth.v1.AuthService.RevokeToken:input_type -> auth.v1.RevokeTokenRequest
	13, // 20: auth.v1.AuthService.Logout:input_type -> auth.v1.LogoutRequest
	15, // 21: auth.v1.AuthService.CheckPermissions:input_type -> auth.v1.CheckPermissionsRequest
	6,  // 22: auth.v1.AuthService.Authenticate:output_type -> auth.v1.AuthenticateResponse
	8,  // 23: auth.v1.AuthService.VerifyToken:output_type -> auth.v1.VerifyTokenResponse
	10, // 24: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenResponse
	12, // 25: auth.v1.AuthService.RevokeToken:output_type -> auth.v1.RevokeTokenResponse
	14, // 26: auth.v1.AuthService.Logout:output_type -> auth.v1.LogoutResponse
	16, // 27: auth.v1.AuthService.CheckPermissions:output_type -> auth.v1.CheckPermissionsResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
