# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/cache/mfa.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'auth/v1/cache/mfa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from tagger import tagger_pb2 as tagger_dot_tagger__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61uth/v1/cache/mfa.proto\x12\rauth.v1.cache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\xd3\x02\n\x07MFACode\x12$\n\x07user_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"\x12\x1e\n\x04\x63ode\x18\x02 \x01(\tB\x10\x9a\x84\x9e\x03\x0bjson:\"code\"\x12\"\n\x06method\x18\x03 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"method\"\x12\x46\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"created_at\"\x12\x46\n\nexpires_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"expires_at\"\x12&\n\x08\x61ttempts\x18\x06 \x01(\x05\x42\x14\x9a\x84\x9e\x03\x0fjson:\"attempts\"\x12&\n\x08verified\x18\x07 \x01(\x08\x42\x14\x9a\x84\x9e\x03\x0fjson:\"verified\"B5Z3erp.localhost/infra/model/auth/v1/cache;authv1cacheb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.cache.mfa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3erp.localhost/infra/model/auth/v1/cache;authv1cache'
  _globals['_MFACODE'].fields_by_name['user_id']._loaded_options = None
  _globals['_MFACODE'].fields_by_name['user_id']._serialized_options = b'\232\204\236\003\016json:\"user_id\"'
  _globals['_MFACODE'].fields_by_name['code']._loaded_options = None
  _globals['_MFACODE'].fields_by_name['code']._serialized_options = b'\232\204\236\003\013json:\"code\"'
  _globals['_MFACODE'].fields_by_name['method']._loaded_options = None
  _globals['_MFACODE'].fields_by_name['method']._serialized_options = b'\232\204\236\003\rjson:\"method\"'
  _globals['_MFACODE'].fields_by_name['created_at']._loaded_options = None
  _globals['_MFACODE'].fields_by_name['created_at']._serialized_options = b'\232\204\236\003\021json:\"created_at\"'
  _globals['_MFACODE'].fields_by_name['expires_at']._loaded_options = None
  _globals['_MFACODE'].fields_by_name['expires_at']._serialized_options = b'\232\204\236\003\021json:\"expires_at\"'
  _globals['_MFACODE'].fields_by_name['attempts']._loaded_options = None
  _globals['_MFACODE'].fields_by_name['attempts']._serialized_options = b'\232\204\236\003\017json:\"attempts\"'
  _globals['_MFACODE'].fields_by_name['verified']._loaded_options = None
  _globals['_MFACODE'].fields_by_name['verified']._serialized_options = b'\232\204\236\003\017json:\"verified\"'
  _globals['_MFACODE']._serialized_start=97
  _globals['_MFACODE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
