// Code generated by MockGen. DO NOT EDIT.
// Source: erp.localhost/internal/auth/service (interfaces: RBACChecker)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_rbac_checker.go -package=mock erp.localhost/internal/auth/service RBACChecker
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	authv1 "erp.localhost/internal/infra/proto/auth/v1"
	infrav1 "erp.localhost/internal/infra/proto/infra/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockRBACChecker is a mock of RBACChecker interface.
type MockRBACChecker struct {
	ctrl     *gomock.Controller
	recorder *MockRBACCheckerMockRecorder
	isgomock struct{}
}

// MockRBACCheckerMockRecorder is the mock recorder for MockRBACChecker.
type MockRBACCheckerMockRecorder struct {
	mock *MockRBACChecker
}

// NewMockRBACChecker creates a new mock instance.
func NewMockRBACChecker(ctrl *gomock.Controller) *MockRBACChecker {
	mock := &MockRBACChecker{ctrl: ctrl}
	mock.recorder = &MockRBACCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBACChecker) EXPECT() *MockRBACCheckerMockRecorder {
	return m.recorder
}

// CreateVerifyPermissionsResourceRequest mocks base method.
func (m *MockRBACChecker) CreateVerifyPermissionsResourceRequest(identifier *infrav1.UserIdentifier, permissionIdentifiers ...string) *authv1.VerifyUserResourceRequest {
	m.ctrl.T.Helper()
	varargs := []any{identifier}
	for _, a := range permissionIdentifiers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateVerifyPermissionsResourceRequest", varargs...)
	ret0, _ := ret[0].(*authv1.VerifyUserResourceRequest)
	return ret0
}

// CreateVerifyPermissionsResourceRequest indicates an expected call of CreateVerifyPermissionsResourceRequest.
func (mr *MockRBACCheckerMockRecorder) CreateVerifyPermissionsResourceRequest(identifier any, permissionIdentifiers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{identifier}, permissionIdentifiers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyPermissionsResourceRequest", reflect.TypeOf((*MockRBACChecker)(nil).CreateVerifyPermissionsResourceRequest), varargs...)
}

// CreateVerifyRolesResourceRequest mocks base method.
func (m *MockRBACChecker) CreateVerifyRolesResourceRequest(identifier *infrav1.UserIdentifier, roles ...string) *authv1.VerifyUserResourceRequest {
	m.ctrl.T.Helper()
	varargs := []any{identifier}
	for _, a := range roles {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateVerifyRolesResourceRequest", varargs...)
	ret0, _ := ret[0].(*authv1.VerifyUserResourceRequest)
	return ret0
}

// CreateVerifyRolesResourceRequest indicates an expected call of CreateVerifyRolesResourceRequest.
func (mr *MockRBACCheckerMockRecorder) CreateVerifyRolesResourceRequest(identifier any, roles ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{identifier}, roles...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyRolesResourceRequest", reflect.TypeOf((*MockRBACChecker)(nil).CreateVerifyRolesResourceRequest), varargs...)
}

// VerifyUserPermissions mocks base method.
func (m *MockRBACChecker) VerifyUserPermissions(ctx context.Context, req *authv1.VerifyUserResourceRequest) (*authv1.VerifyResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserPermissions", ctx, req)
	ret0, _ := ret[0].(*authv1.VerifyResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserPermissions indicates an expected call of VerifyUserPermissions.
func (mr *MockRBACCheckerMockRecorder) VerifyUserPermissions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserPermissions", reflect.TypeOf((*MockRBACChecker)(nil).VerifyUserPermissions), ctx, req)
}

// VerifyUserRoles mocks base method.
func (m *MockRBACChecker) VerifyUserRoles(ctx context.Context, req *authv1.VerifyUserResourceRequest) (*authv1.VerifyResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserRoles", ctx, req)
	ret0, _ := ret[0].(*authv1.VerifyResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserRoles indicates an expected call of VerifyUserRoles.
func (mr *MockRBACCheckerMockRecorder) VerifyUserRoles(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserRoles", reflect.TypeOf((*MockRBACChecker)(nil).VerifyUserRoles), ctx, req)
}
