# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/cache/presence.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'auth/v1/cache/presence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from tagger import tagger_pb2 as tagger_dot_tagger__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61uth/v1/cache/presence.proto\x12\rauth.v1.cache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\xfa\x01\n\nActiveUser\x12$\n\x07user_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"\x12(\n\ttenant_id\x18\x02 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"tenant_id\"\x12*\n\nsession_id\x18\x03 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"session_id\"\x12L\n\rlast_activity\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x19\x9a\x84\x9e\x03\x14json:\"last_activity\"\x12\"\n\x06status\x18\x05 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"status\"B5Z3erp.localhost/infra/model/auth/v1/cache;authv1cacheb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.cache.presence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3erp.localhost/infra/model/auth/v1/cache;authv1cache'
  _globals['_ACTIVEUSER'].fields_by_name['user_id']._loaded_options = None
  _globals['_ACTIVEUSER'].fields_by_name['user_id']._serialized_options = b'\232\204\236\003\016json:\"user_id\"'
  _globals['_ACTIVEUSER'].fields_by_name['tenant_id']._loaded_options = None
  _globals['_ACTIVEUSER'].fields_by_name['tenant_id']._serialized_options = b'\232\204\236\003\020json:\"tenant_id\"'
  _globals['_ACTIVEUSER'].fields_by_name['session_id']._loaded_options = None
  _globals['_ACTIVEUSER'].fields_by_name['session_id']._serialized_options = b'\232\204\236\003\021json:\"session_id\"'
  _globals['_ACTIVEUSER'].fields_by_name['last_activity']._loaded_options = None
  _globals['_ACTIVEUSER'].fields_by_name['last_activity']._serialized_options = b'\232\204\236\003\024json:\"last_activity\"'
  _globals['_ACTIVEUSER'].fields_by_name['status']._loaded_options = None
  _globals['_ACTIVEUSER'].fields_by_name['status']._serialized_options = b'\232\204\236\003\rjson:\"status\"'
  _globals['_ACTIVEUSER']._serialized_start=102
  _globals['_ACTIVEUSER']._serialized_end=352
# @@protoc_insertion_point(module_scope)
