# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/cache/rbac.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'auth/v1/cache/rbac.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from tagger import tagger_pb2 as tagger_dot_tagger__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61uth/v1/cache/rbac.proto\x12\rauth.v1.cache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\x80\x02\n\x14UserPermissionsCache\x12$\n\x07user_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"\x12(\n\ttenant_id\x18\x02 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"tenant_id\"\x12,\n\x0bpermissions\x18\x03 \x03(\tB\x17\x9a\x84\x9e\x03\x12json:\"permissions\"\x12\x44\n\tcached_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x15\x9a\x84\x9e\x03\x10json:\"cached_at\"\x12$\n\x07version\x18\x05 \x01(\x05\x42\x13\x9a\x84\x9e\x03\x0ejson:\"version\"\"\x8a\x02\n\x0eUserRolesCache\x12$\n\x07user_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"\x12(\n\ttenant_id\x18\x02 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"tenant_id\"\x12<\n\x05roles\x18\x03 \x03(\x0b\x32\x1a.auth.v1.cache.RoleSummaryB\x11\x9a\x84\x9e\x03\x0cjson:\"roles\"\x12\x44\n\tcached_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x15\x9a\x84\x9e\x03\x10json:\"cached_at\"\x12$\n\x07version\x18\x05 \x01(\x05\x42\x13\x9a\x84\x9e\x03\x0ejson:\"version\"\"{\n\x0bRoleSummary\x12$\n\x07role_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"role_id\"\x12\x1e\n\x04name\x18\x02 \x01(\tB\x10\x9a\x84\x9e\x03\x0bjson:\"name\"\x12&\n\x08priority\x18\x03 \x01(\x05\x42\x14\x9a\x84\x9e\x03\x0fjson:\"priority\"\"\x80\x02\n\x14RolePermissionsCache\x12$\n\x07role_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"role_id\"\x12(\n\ttenant_id\x18\x02 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"tenant_id\"\x12,\n\x0bpermissions\x18\x03 \x03(\tB\x17\x9a\x84\x9e\x03\x12json:\"permissions\"\x12\x44\n\tcached_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x15\x9a\x84\x9e\x03\x10json:\"cached_at\"\x12$\n\x07version\x18\x05 \x01(\x05\x42\x13\x9a\x84\x9e\x03\x0ejson:\"version\"B5Z3erp.localhost/infra/model/auth/v1/cache;authv1cacheb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.cache.rbac_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3erp.localhost/infra/model/auth/v1/cache;authv1cache'
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['user_id']._loaded_options = None
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['user_id']._serialized_options = b'\232\204\236\003\016json:\"user_id\"'
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['tenant_id']._loaded_options = None
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['tenant_id']._serialized_options = b'\232\204\236\003\020json:\"tenant_id\"'
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['permissions']._loaded_options = None
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['permissions']._serialized_options = b'\232\204\236\003\022json:\"permissions\"'
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['cached_at']._loaded_options = None
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['cached_at']._serialized_options = b'\232\204\236\003\020json:\"cached_at\"'
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['version']._loaded_options = None
  _globals['_USERPERMISSIONSCACHE'].fields_by_name['version']._serialized_options = b'\232\204\236\003\016json:\"version\"'
  _globals['_USERROLESCACHE'].fields_by_name['user_id']._loaded_options = None
  _globals['_USERROLESCACHE'].fields_by_name['user_id']._serialized_options = b'\232\204\236\003\016json:\"user_id\"'
  _globals['_USERROLESCACHE'].fields_by_name['tenant_id']._loaded_options = None
  _globals['_USERROLESCACHE'].fields_by_name['tenant_id']._serialized_options = b'\232\204\236\003\020json:\"tenant_id\"'
  _globals['_USERROLESCACHE'].fields_by_name['roles']._loaded_options = None
  _globals['_USERROLESCACHE'].fields_by_name['roles']._serialized_options = b'\232\204\236\003\014json:\"roles\"'
  _globals['_USERROLESCACHE'].fields_by_name['cached_at']._loaded_options = None
  _globals['_USERROLESCACHE'].fields_by_name['cached_at']._serialized_options = b'\232\204\236\003\020json:\"cached_at\"'
  _globals['_USERROLESCACHE'].fields_by_name['version']._loaded_options = None
  _globals['_USERROLESCACHE'].fields_by_name['version']._serialized_options = b'\232\204\236\003\016json:\"version\"'
  _globals['_ROLESUMMARY'].fields_by_name['role_id']._loaded_options = None
  _globals['_ROLESUMMARY'].fields_by_name['role_id']._serialized_options = b'\232\204\236\003\016json:\"role_id\"'
  _globals['_ROLESUMMARY'].fields_by_name['name']._loaded_options = None
  _globals['_ROLESUMMARY'].fields_by_name['name']._serialized_options = b'\232\204\236\003\013json:\"name\"'
  _globals['_ROLESUMMARY'].fields_by_name['priority']._loaded_options = None
  _globals['_ROLESUMMARY'].fields_by_name['priority']._serialized_options = b'\232\204\236\003\017json:\"priority\"'
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['role_id']._loaded_options = None
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['role_id']._serialized_options = b'\232\204\236\003\016json:\"role_id\"'
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['tenant_id']._loaded_options = None
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['tenant_id']._serialized_options = b'\232\204\236\003\020json:\"tenant_id\"'
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['permissions']._loaded_options = None
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['permissions']._serialized_options = b'\232\204\236\003\022json:\"permissions\"'
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['cached_at']._loaded_options = None
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['cached_at']._serialized_options = b'\232\204\236\003\020json:\"cached_at\"'
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['version']._loaded_options = None
  _globals['_ROLEPERMISSIONSCACHE'].fields_by_name['version']._serialized_options = b'\232\204\236\003\016json:\"version\"'
  _globals['_USERPERMISSIONSCACHE']._serialized_start=98
  _globals['_USERPERMISSIONSCACHE']._serialized_end=354
  _globals['_USERROLESCACHE']._serialized_start=357
  _globals['_USERROLESCACHE']._serialized_end=623
  _globals['_ROLESUMMARY']._serialized_start=625
  _globals['_ROLESUMMARY']._serialized_end=748
  _globals['_ROLEPERMISSIONSCACHE']._serialized_start=751
  _globals['_ROLEPERMISSIONSCACHE']._serialized_end=1007
# @@protoc_insertion_point(module_scope)
