# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/cache/token.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth/v1/cache/token.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from lib.model.tagger import tagger_pb2 as tagger_dot_tagger__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61uth/v1/cache/token.proto\x12\rauth.v1.cache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\x91\x03\n\rTokenMetadata\x12\x1c\n\x03jti\x18\x01 \x01(\tB\x0f\x9a\x84\x9e\x03\njson:\"jti\"\x12$\n\x07user_id\x18\x02 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"\x12(\n\ttenant_id\x18\x03 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"tenant_id\"\x12\x44\n\tissued_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x15\x9a\x84\x9e\x03\x10json:\"issued_at\"\x12\x46\n\nexpires_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"expires_at\"\x12*\n\nip_address\x18\x06 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"ip_address\"\x12*\n\nuser_agent\x18\x07 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"user_agent\"\x12,\n\x06scopes\x18\x08 \x03(\tB\x1c\x9a\x84\x9e\x03\x17json:\"scopes,omitempty\"B5Z3erp.localhost/infra/model/auth/v1/cache;authv1cacheb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.cache.token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3erp.localhost/infra/model/auth/v1/cache;authv1cache'
  _globals['_TOKENMETADATA'].fields_by_name['jti']._loaded_options = None
  _globals['_TOKENMETADATA'].fields_by_name['jti']._serialized_options = b'\232\204\236\003\njson:\"jti\"'
  _globals['_TOKENMETADATA'].fields_by_name['user_id']._loaded_options = None
  _globals['_TOKENMETADATA'].fields_by_name['user_id']._serialized_options = b'\232\204\236\003\016json:\"user_id\"'
  _globals['_TOKENMETADATA'].fields_by_name['tenant_id']._loaded_options = None
  _globals['_TOKENMETADATA'].fields_by_name['tenant_id']._serialized_options = b'\232\204\236\003\020json:\"tenant_id\"'
  _globals['_TOKENMETADATA'].fields_by_name['issued_at']._loaded_options = None
  _globals['_TOKENMETADATA'].fields_by_name['issued_at']._serialized_options = b'\232\204\236\003\020json:\"issued_at\"'
  _globals['_TOKENMETADATA'].fields_by_name['expires_at']._loaded_options = None
  _globals['_TOKENMETADATA'].fields_by_name['expires_at']._serialized_options = b'\232\204\236\003\021json:\"expires_at\"'
  _globals['_TOKENMETADATA'].fields_by_name['ip_address']._loaded_options = None
  _globals['_TOKENMETADATA'].fields_by_name['ip_address']._serialized_options = b'\232\204\236\003\021json:\"ip_address\"'
  _globals['_TOKENMETADATA'].fields_by_name['user_agent']._loaded_options = None
  _globals['_TOKENMETADATA'].fields_by_name['user_agent']._serialized_options = b'\232\204\236\003\021json:\"user_agent\"'
  _globals['_TOKENMETADATA'].fields_by_name['scopes']._loaded_options = None
  _globals['_TOKENMETADATA'].fields_by_name['scopes']._serialized_options = b'\232\204\236\003\027json:\"scopes,omitempty\"'
  _globals['_TOKENMETADATA']._serialized_start=99
  _globals['_TOKENMETADATA']._serialized_end=500
# @@protoc_insertion_point(module_scope)
