// source: auth/v1/cache/security.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var tagger_tagger_pb = require('../../../tagger/tagger_pb.js');
goog.object.extend(proto, tagger_tagger_pb);
goog.exportSymbol('proto.auth.v1.cache.LoginAttempts', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.auth.v1.cache.LoginAttempts = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.auth.v1.cache.LoginAttempts.repeatedFields_, null);
};
goog.inherits(proto.auth.v1.cache.LoginAttempts, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.auth.v1.cache.LoginAttempts.displayName = 'proto.auth.v1.cache.LoginAttempts';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.auth.v1.cache.LoginAttempts.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.auth.v1.cache.LoginAttempts.prototype.toObject = function(opt_includeInstance) {
  return proto.auth.v1.cache.LoginAttempts.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.auth.v1.cache.LoginAttempts} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.auth.v1.cache.LoginAttempts.toObject = function(includeInstance, msg) {
  var f, obj = {
    identifier: jspb.Message.getFieldWithDefault(msg, 1, ""),
    attempts: jspb.Message.getFieldWithDefault(msg, 2, 0),
    firstAttempt: (f = msg.getFirstAttempt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    lastAttempt: (f = msg.getLastAttempt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    locked: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    lockedUntil: (f = msg.getLockedUntil()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    failedIpsList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.auth.v1.cache.LoginAttempts}
 */
proto.auth.v1.cache.LoginAttempts.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.auth.v1.cache.LoginAttempts;
  return proto.auth.v1.cache.LoginAttempts.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.auth.v1.cache.LoginAttempts} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.auth.v1.cache.LoginAttempts}
 */
proto.auth.v1.cache.LoginAttempts.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentifier(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAttempts(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFirstAttempt(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastAttempt(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLocked(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLockedUntil(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addFailedIps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.auth.v1.cache.LoginAttempts.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.auth.v1.cache.LoginAttempts.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.auth.v1.cache.LoginAttempts} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.auth.v1.cache.LoginAttempts.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentifier();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAttempts();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getFirstAttempt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLastAttempt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLocked();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getLockedUntil();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getFailedIpsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
};


/**
 * optional string identifier = 1;
 * @return {string}
 */
proto.auth.v1.cache.LoginAttempts.prototype.getIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.setIdentifier = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 attempts = 2;
 * @return {number}
 */
proto.auth.v1.cache.LoginAttempts.prototype.getAttempts = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.setAttempts = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp first_attempt = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.auth.v1.cache.LoginAttempts.prototype.getFirstAttempt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
*/
proto.auth.v1.cache.LoginAttempts.prototype.setFirstAttempt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.clearFirstAttempt = function() {
  return this.setFirstAttempt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.auth.v1.cache.LoginAttempts.prototype.hasFirstAttempt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp last_attempt = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.auth.v1.cache.LoginAttempts.prototype.getLastAttempt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
*/
proto.auth.v1.cache.LoginAttempts.prototype.setLastAttempt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.clearLastAttempt = function() {
  return this.setLastAttempt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.auth.v1.cache.LoginAttempts.prototype.hasLastAttempt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool locked = 5;
 * @return {boolean}
 */
proto.auth.v1.cache.LoginAttempts.prototype.getLocked = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.setLocked = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional google.protobuf.Timestamp locked_until = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.auth.v1.cache.LoginAttempts.prototype.getLockedUntil = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
*/
proto.auth.v1.cache.LoginAttempts.prototype.setLockedUntil = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.clearLockedUntil = function() {
  return this.setLockedUntil(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.auth.v1.cache.LoginAttempts.prototype.hasLockedUntil = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated string failed_ips = 7;
 * @return {!Array<string>}
 */
proto.auth.v1.cache.LoginAttempts.prototype.getFailedIpsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.setFailedIpsList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.addFailedIps = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.auth.v1.cache.LoginAttempts} returns this
 */
proto.auth.v1.cache.LoginAttempts.prototype.clearFailedIpsList = function() {
  return this.setFailedIpsList([]);
};


goog.object.extend(exports, proto.auth.v1.cache);
