// Code generated by MockGen. DO NOT EDIT.
// Source: erp.localhost/internal/auth/token/handlers (interfaces: TokenHandler)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_token_handler.go -package=mocks erp.localhost/internal/auth/token/handlers TokenHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenHandler is a mock of TokenHandler interface.
type MockTokenHandler[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockTokenHandlerMockRecorder[T]
	isgomock struct{}
}

// MockTokenHandlerMockRecorder is the mock recorder for MockTokenHandler.
type MockTokenHandlerMockRecorder[T any] struct {
	mock *MockTokenHandler[T]
}

// NewMockTokenHandler creates a new mock instance.
func NewMockTokenHandler[T any](ctrl *gomock.Controller) *MockTokenHandler[T] {
	mock := &MockTokenHandler[T]{ctrl: ctrl}
	mock.recorder = &MockTokenHandlerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenHandler[T]) EXPECT() *MockTokenHandlerMockRecorder[T] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTokenHandler[T]) Delete(tenantID, userID, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tenantID, userID, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTokenHandlerMockRecorder[T]) Delete(tenantID, userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTokenHandler[T])(nil).Delete), tenantID, userID, tokenID)
}

// GetAll mocks base method.
func (m *MockTokenHandler[T]) GetAll(tenantID, userID string) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", tenantID, userID)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTokenHandlerMockRecorder[T]) GetAll(tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTokenHandler[T])(nil).GetAll), tenantID, userID)
}

// GetOne mocks base method.
func (m *MockTokenHandler[T]) GetOne(tenantID, userID, tokenID string) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", tenantID, userID, tokenID)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockTokenHandlerMockRecorder[T]) GetOne(tenantID, userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockTokenHandler[T])(nil).GetOne), tenantID, userID, tokenID)
}

// Revoke mocks base method.
func (m *MockTokenHandler[T]) Revoke(tenantID, userID, tokenID, revokedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", tenantID, userID, tokenID, revokedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenHandlerMockRecorder[T]) Revoke(tenantID, userID, tokenID, revokedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenHandler[T])(nil).Revoke), tenantID, userID, tokenID, revokedBy)
}

// RevokeAll mocks base method.
func (m *MockTokenHandler[T]) RevokeAll(tenantID, userID, revokedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAll", tenantID, userID, revokedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAll indicates an expected call of RevokeAll.
func (mr *MockTokenHandlerMockRecorder[T]) RevokeAll(tenantID, userID, revokedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAll", reflect.TypeOf((*MockTokenHandler[T])(nil).RevokeAll), tenantID, userID, revokedBy)
}

// Store mocks base method.
func (m *MockTokenHandler[T]) Store(tenantID, userID, tokenID string, value T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", tenantID, userID, tokenID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTokenHandlerMockRecorder[T]) Store(tenantID, userID, tokenID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTokenHandler[T])(nil).Store), tenantID, userID, tokenID, value)
}

// Validate mocks base method.
func (m *MockTokenHandler[T]) Validate(tenantID, userID, tokenID string) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", tenantID, userID, tokenID)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockTokenHandlerMockRecorder[T]) Validate(tenantID, userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTokenHandler[T])(nil).Validate), tenantID, userID, tokenID)
}
