// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/v1/cache/service_config_cache.proto

package configcache

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceConfigCache represents cached service configuration
// Stored in: service_config_cache:{service_name}:{environment}:{tenant_id} (Redis Hash)
// TTL: 30 minutes
type ServiceConfigCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,5,opt,name=config,proto3" json:"config"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version"`
	CachedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfigCache) Reset() {
	*x = ServiceConfigCache{}
	mi := &file_config_v1_cache_service_config_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfigCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfigCache) ProtoMessage() {}

func (x *ServiceConfigCache) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_cache_service_config_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfigCache.ProtoReflect.Descriptor instead.
func (*ServiceConfigCache) Descriptor() ([]byte, []int) {
	return file_config_v1_cache_service_config_cache_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceConfigCache) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ServiceConfigCache) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceConfigCache) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ServiceConfigCache) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ServiceConfigCache) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ServiceConfigCache) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServiceConfigCache) GetCachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CachedAt
	}
	return nil
}

func (x *ServiceConfigCache) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ConfigVersionCache tracks the latest version of each config
// Stored in: config_versions:{service_name}:{environment} (Redis Hash)
// Used for cache invalidation when config changes
type ConfigVersionCache struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name"`
	Environment    string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment"`
	LatestVersion  int32                  `protobuf:"varint,3,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version"`
	TenantVersions map[string]int32       `protobuf:"bytes,4,rep,name=tenant_versions,json=tenantVersions,proto3" json:"tenant_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigVersionCache) Reset() {
	*x = ConfigVersionCache{}
	mi := &file_config_v1_cache_service_config_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVersionCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVersionCache) ProtoMessage() {}

func (x *ConfigVersionCache) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_cache_service_config_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVersionCache.ProtoReflect.Descriptor instead.
func (*ConfigVersionCache) Descriptor() ([]byte, []int) {
	return file_config_v1_cache_service_config_cache_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigVersionCache) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ConfigVersionCache) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ConfigVersionCache) GetLatestVersion() int32 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

func (x *ConfigVersionCache) GetTenantVersions() map[string]int32 {
	if x != nil {
		return x.TenantVersions
	}
	return nil
}

func (x *ConfigVersionCache) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_config_v1_cache_service_config_cache_proto protoreflect.FileDescriptor

const file_config_v1_cache_service_config_cache_proto_rawDesc = "" +
	"\n" +
	"*config/v1/cache/service_config_cache.proto\x12\x0fconfig.v1.cache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13tagger/tagger.proto\"\x95\x04\n" +
	"\x12ServiceConfigCache\x122\n" +
	"\tconfig_id\x18\x01 \x01(\tB\x15\x9a\x84\x9e\x03\x10json:\"config_id\"R\bconfigId\x12;\n" +
	"\fservice_name\x18\x02 \x01(\tB\x18\x9a\x84\x9e\x03\x13json:\"service_name\"R\vserviceName\x129\n" +
	"\venvironment\x18\x03 \x01(\tB\x17\x9a\x84\x9e\x03\x12json:\"environment\"R\venvironment\x12<\n" +
	"\ttenant_id\x18\x04 \x01(\tB\x1f\x9a\x84\x9e\x03\x1ajson:\"tenant_id,omitempty\"R\btenantId\x12C\n" +
	"\x06config\x18\x05 \x01(\v2\x17.google.protobuf.StructB\x12\x9a\x84\x9e\x03\rjson:\"config\"R\x06config\x12-\n" +
	"\aversion\x18\x06 \x01(\x05B\x13\x9a\x84\x9e\x03\x0ejson:\"version\"R\aversion\x12N\n" +
	"\tcached_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x15\x9a\x84\x9e\x03\x10json:\"cached_at\"R\bcachedAt\x12Q\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"expires_at\"R\texpiresAt\"\xef\x03\n" +
	"\x12ConfigVersionCache\x12;\n" +
	"\fservice_name\x18\x01 \x01(\tB\x18\x9a\x84\x9e\x03\x13json:\"service_name\"R\vserviceName\x129\n" +
	"\venvironment\x18\x02 \x01(\tB\x17\x9a\x84\x9e\x03\x12json:\"environment\"R\venvironment\x12A\n" +
	"\x0elatest_version\x18\x03 \x01(\x05B\x1a\x9a\x84\x9e\x03\x15json:\"latest_version\"R\rlatestVersion\x12\x87\x01\n" +
	"\x0ftenant_versions\x18\x04 \x03(\v27.config.v1.cache.ConfigVersionCache.TenantVersionsEntryB%\x9a\x84\x9e\x03 json:\"tenant_versions,omitempty\"R\x0etenantVersions\x12Q\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"updated_at\"R\tupdatedAt\x1aA\n" +
	"\x13TenantVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B@Z>erp.localhost/internal/infra/model/config/v1/cache;configcacheb\x06proto3"

var (
	file_config_v1_cache_service_config_cache_proto_rawDescOnce sync.Once
	file_config_v1_cache_service_config_cache_proto_rawDescData []byte
)

func file_config_v1_cache_service_config_cache_proto_rawDescGZIP() []byte {
	file_config_v1_cache_service_config_cache_proto_rawDescOnce.Do(func() {
		file_config_v1_cache_service_config_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_cache_service_config_cache_proto_rawDesc), len(file_config_v1_cache_service_config_cache_proto_rawDesc)))
	})
	return file_config_v1_cache_service_config_cache_proto_rawDescData
}

var file_config_v1_cache_service_config_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_config_v1_cache_service_config_cache_proto_goTypes = []any{
	(*ServiceConfigCache)(nil),    // 0: config.v1.cache.ServiceConfigCache
	(*ConfigVersionCache)(nil),    // 1: config.v1.cache.ConfigVersionCache
	nil,                           // 2: config.v1.cache.ConfigVersionCache.TenantVersionsEntry
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_config_v1_cache_service_config_cache_proto_depIdxs = []int32{
	3, // 0: config.v1.cache.ServiceConfigCache.config:type_name -> google.protobuf.Struct
	4, // 1: config.v1.cache.ServiceConfigCache.cached_at:type_name -> google.protobuf.Timestamp
	4, // 2: config.v1.cache.ServiceConfigCache.expires_at:type_name -> google.protobuf.Timestamp
	2, // 3: config.v1.cache.ConfigVersionCache.tenant_versions:type_name -> config.v1.cache.ConfigVersionCache.TenantVersionsEntry
	4, // 4: config.v1.cache.ConfigVersionCache.updated_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_config_v1_cache_service_config_cache_proto_init() }
func file_config_v1_cache_service_config_cache_proto_init() {
	if File_config_v1_cache_service_config_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_cache_service_config_cache_proto_rawDesc), len(file_config_v1_cache_service_config_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_cache_service_config_cache_proto_goTypes,
		DependencyIndexes: file_config_v1_cache_service_config_cache_proto_depIdxs,
		MessageInfos:      file_config_v1_cache_service_config_cache_proto_msgTypes,
	}.Build()
	File_config_v1_cache_service_config_cache_proto = out.File
	file_config_v1_cache_service_config_cache_proto_goTypes = nil
	file_config_v1_cache_service_config_cache_proto_depIdxs = nil
}
