// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth/v1/cache/mfa.proto

package authcache

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MFACode represents a temporary MFA code
type MFACode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at"`
	Attempts      int32                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts"`
	Verified      bool                   `protobuf:"varint,7,opt,name=verified,proto3" json:"verified"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFACode) Reset() {
	*x = MFACode{}
	mi := &file_auth_v1_cache_mfa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFACode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFACode) ProtoMessage() {}

func (x *MFACode) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_cache_mfa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFACode.ProtoReflect.Descriptor instead.
func (*MFACode) Descriptor() ([]byte, []int) {
	return file_auth_v1_cache_mfa_proto_rawDescGZIP(), []int{0}
}

func (x *MFACode) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MFACode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MFACode) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MFACode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MFACode) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *MFACode) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *MFACode) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_auth_v1_cache_mfa_proto protoreflect.FileDescriptor

const file_auth_v1_cache_mfa_proto_rawDesc = "" +
	"\n" +
	"\x17auth/v1/cache/mfa.proto\x12\rauth.v1.cache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\x93\x03\n" +
	"\aMFACode\x12,\n" +
	"\auser_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"R\x06userId\x12$\n" +
	"\x04code\x18\x02 \x01(\tB\x10\x9a\x84\x9e\x03\vjson:\"code\"R\x04code\x12*\n" +
	"\x06method\x18\x03 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"method\"R\x06method\x12Q\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"created_at\"R\tcreatedAt\x12Q\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"expires_at\"R\texpiresAt\x120\n" +
	"\battempts\x18\x06 \x01(\x05B\x14\x9a\x84\x9e\x03\x0fjson:\"attempts\"R\battempts\x120\n" +
	"\bverified\x18\a \x01(\bB\x14\x9a\x84\x9e\x03\x0fjson:\"verified\"R\bverifiedB<Z:erp.localhost/internal/infra/model/auth/v1/cache;authcacheb\x06proto3"

var (
	file_auth_v1_cache_mfa_proto_rawDescOnce sync.Once
	file_auth_v1_cache_mfa_proto_rawDescData []byte
)

func file_auth_v1_cache_mfa_proto_rawDescGZIP() []byte {
	file_auth_v1_cache_mfa_proto_rawDescOnce.Do(func() {
		file_auth_v1_cache_mfa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_cache_mfa_proto_rawDesc), len(file_auth_v1_cache_mfa_proto_rawDesc)))
	})
	return file_auth_v1_cache_mfa_proto_rawDescData
}

var file_auth_v1_cache_mfa_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_v1_cache_mfa_proto_goTypes = []any{
	(*MFACode)(nil),               // 0: auth.v1.cache.MFACode
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_auth_v1_cache_mfa_proto_depIdxs = []int32{
	1, // 0: auth.v1.cache.MFACode.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: auth.v1.cache.MFACode.expires_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_v1_cache_mfa_proto_init() }
func file_auth_v1_cache_mfa_proto_init() {
	if File_auth_v1_cache_mfa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_cache_mfa_proto_rawDesc), len(file_auth_v1_cache_mfa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_cache_mfa_proto_goTypes,
		DependencyIndexes: file_auth_v1_cache_mfa_proto_depIdxs,
		MessageInfos:      file_auth_v1_cache_mfa_proto_msgTypes,
	}.Build()
	File_auth_v1_cache_mfa_proto = out.File
	file_auth_v1_cache_mfa_proto_goTypes = nil
	file_auth_v1_cache_mfa_proto_depIdxs = nil
}
