// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth/v1/cache/password.proto

package authcache

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PasswordResetToken represents a password reset token
type PasswordResetToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at"`
	Used          bool                   `protobuf:"varint,6,opt,name=used,proto3" json:"used"`
	UsedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetToken) Reset() {
	*x = PasswordResetToken{}
	mi := &file_auth_v1_cache_password_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetToken) ProtoMessage() {}

func (x *PasswordResetToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_cache_password_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetToken.ProtoReflect.Descriptor instead.
func (*PasswordResetToken) Descriptor() ([]byte, []int) {
	return file_auth_v1_cache_password_proto_rawDescGZIP(), []int{0}
}

func (x *PasswordResetToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PasswordResetToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PasswordResetToken) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordResetToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PasswordResetToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PasswordResetToken) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *PasswordResetToken) GetUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UsedAt
	}
	return nil
}

var File_auth_v1_cache_password_proto protoreflect.FileDescriptor

const file_auth_v1_cache_password_proto_rawDesc = "" +
	"\n" +
	"\x1cauth/v1/cache/password.proto\x12\rauth.v1.cache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\xb4\x03\n" +
	"\x12PasswordResetToken\x12'\n" +
	"\x05token\x18\x01 \x01(\tB\x11\x9a\x84\x9e\x03\fjson:\"token\"R\x05token\x12,\n" +
	"\auser_id\x18\x02 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"R\x06userId\x12'\n" +
	"\x05email\x18\x03 \x01(\tB\x11\x9a\x84\x9e\x03\fjson:\"email\"R\x05email\x12Q\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"created_at\"R\tcreatedAt\x12Q\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x16\x9a\x84\x9e\x03\x11json:\"expires_at\"R\texpiresAt\x12$\n" +
	"\x04used\x18\x06 \x01(\bB\x10\x9a\x84\x9e\x03\vjson:\"used\"R\x04used\x12R\n" +
	"\aused_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x1d\x9a\x84\x9e\x03\x18json:\"used_at,omitempty\"R\x06usedAtB<Z:erp.localhost/internal/infra/model/auth/v1/cache;authcacheb\x06proto3"

var (
	file_auth_v1_cache_password_proto_rawDescOnce sync.Once
	file_auth_v1_cache_password_proto_rawDescData []byte
)

func file_auth_v1_cache_password_proto_rawDescGZIP() []byte {
	file_auth_v1_cache_password_proto_rawDescOnce.Do(func() {
		file_auth_v1_cache_password_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_cache_password_proto_rawDesc), len(file_auth_v1_cache_password_proto_rawDesc)))
	})
	return file_auth_v1_cache_password_proto_rawDescData
}

var file_auth_v1_cache_password_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_v1_cache_password_proto_goTypes = []any{
	(*PasswordResetToken)(nil),    // 0: auth.v1.cache.PasswordResetToken
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_auth_v1_cache_password_proto_depIdxs = []int32{
	1, // 0: auth.v1.cache.PasswordResetToken.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: auth.v1.cache.PasswordResetToken.expires_at:type_name -> google.protobuf.Timestamp
	1, // 2: auth.v1.cache.PasswordResetToken.used_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_v1_cache_password_proto_init() }
func file_auth_v1_cache_password_proto_init() {
	if File_auth_v1_cache_password_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_cache_password_proto_rawDesc), len(file_auth_v1_cache_password_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_cache_password_proto_goTypes,
		DependencyIndexes: file_auth_v1_cache_password_proto_depIdxs,
		MessageInfos:      file_auth_v1_cache_password_proto_msgTypes,
	}.Build()
	File_auth_v1_cache_password_proto = out.File
	file_auth_v1_cache_password_proto_goTypes = nil
	file_auth_v1_cache_password_proto_depIdxs = nil
}
