// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/v1/address.proto

package corev1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address is a shared address type used across core models
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street" bson:"street"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city" bson:"city"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state" bson:"state"`
	Zip           string                 `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip" bson:"zip"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country" bson:"country"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_core_v1_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_core_v1_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_core_v1_address_proto protoreflect.FileDescriptor

const file_core_v1_address_proto_rawDesc = "" +
	"\n" +
	"\x15core/v1/address.proto\x12\acore.v1\x1a\x13tagger/tagger.proto\"\x97\x02\n" +
	"\aAddress\x128\n" +
	"\x06street\x18\x01 \x01(\tB \x9a\x84\x9e\x03\x1bbson:\"street\" json:\"street\"R\x06street\x120\n" +
	"\x04city\x18\x02 \x01(\tB\x1c\x9a\x84\x9e\x03\x17bson:\"city\" json:\"city\"R\x04city\x124\n" +
	"\x05state\x18\x03 \x01(\tB\x1e\x9a\x84\x9e\x03\x19bson:\"state\" json:\"state\"R\x05state\x12,\n" +
	"\x03zip\x18\x04 \x01(\tB\x1a\x9a\x84\x9e\x03\x15bson:\"zip\" json:\"zip\"R\x03zip\x12<\n" +
	"\acountry\x18\x05 \x01(\tB\"\x9a\x84\x9e\x03\x1dbson:\"country\" json:\"country\"R\acountryB3Z1erp.localhost/internal/infra/model/core/v1;corev1b\x06proto3"

var (
	file_core_v1_address_proto_rawDescOnce sync.Once
	file_core_v1_address_proto_rawDescData []byte
)

func file_core_v1_address_proto_rawDescGZIP() []byte {
	file_core_v1_address_proto_rawDescOnce.Do(func() {
		file_core_v1_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_address_proto_rawDesc), len(file_core_v1_address_proto_rawDesc)))
	})
	return file_core_v1_address_proto_rawDescData
}

var file_core_v1_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_v1_address_proto_goTypes = []any{
	(*Address)(nil), // 0: core.v1.Address
}
var file_core_v1_address_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_v1_address_proto_init() }
func file_core_v1_address_proto_init() {
	if File_core_v1_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_address_proto_rawDesc), len(file_core_v1_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_address_proto_goTypes,
		DependencyIndexes: file_core_v1_address_proto_depIdxs,
		MessageInfos:      file_core_v1_address_proto_msgTypes,
	}.Build()
	File_core_v1_address_proto = out.File
	file_core_v1_address_proto_goTypes = nil
	file_core_v1_address_proto_depIdxs = nil
}
