// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/v1/inventory.proto

package corev1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Inventory model for MongoDB core_db.inventory collection
type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id,omitempty"`
	InventoryId   string                 `protobuf:"bytes,2,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id" bson:"inventory_id"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id" bson:"tenant_id"`
	ProductId     string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id" bson:"product_id"`
	WarehouseId   string                 `protobuf:"bytes,5,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id" bson:"warehouse_id"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity" bson:"quantity"`
	Reserved      int32                  `protobuf:"varint,7,opt,name=reserved,proto3" json:"reserved" bson:"reserved"`
	Available     int32                  `protobuf:"varint,8,opt,name=available,proto3" json:"available" bson:"available"`
	Location      *InventoryLocation     `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty" bson:"location,omitempty"`
	BatchNumber   string                 `protobuf:"bytes,10,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty" bson:"batch_number,omitempty"`
	SerialNumbers []string               `protobuf:"bytes,11,rep,name=serial_numbers,json=serialNumbers,proto3" json:"serial_numbers,omitempty" bson:"serial_numbers,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty" bson:"expiry_date,omitempty"`
	ReceivedDate  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=received_date,json=receivedDate,proto3" json:"received_date" bson:"received_date"`
	Cost          float64                `protobuf:"fixed64,14,opt,name=cost,proto3" json:"cost" bson:"cost"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at" bson:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_core_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_core_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Inventory) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *Inventory) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Inventory) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Inventory) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *Inventory) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Inventory) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *Inventory) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *Inventory) GetLocation() *InventoryLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Inventory) GetBatchNumber() string {
	if x != nil {
		return x.BatchNumber
	}
	return ""
}

func (x *Inventory) GetSerialNumbers() []string {
	if x != nil {
		return x.SerialNumbers
	}
	return nil
}

func (x *Inventory) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *Inventory) GetReceivedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedDate
	}
	return nil
}

func (x *Inventory) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Inventory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type InventoryLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aisle         string                 `protobuf:"bytes,1,opt,name=aisle,proto3" json:"aisle,omitempty" bson:"aisle,omitempty"`
	Shelf         string                 `protobuf:"bytes,2,opt,name=shelf,proto3" json:"shelf,omitempty" bson:"shelf,omitempty"`
	Bin           string                 `protobuf:"bytes,3,opt,name=bin,proto3" json:"bin,omitempty" bson:"bin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryLocation) Reset() {
	*x = InventoryLocation{}
	mi := &file_core_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryLocation) ProtoMessage() {}

func (x *InventoryLocation) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryLocation.ProtoReflect.Descriptor instead.
func (*InventoryLocation) Descriptor() ([]byte, []int) {
	return file_core_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryLocation) GetAisle() string {
	if x != nil {
		return x.Aisle
	}
	return ""
}

func (x *InventoryLocation) GetShelf() string {
	if x != nil {
		return x.Shelf
	}
	return ""
}

func (x *InventoryLocation) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

var File_core_v1_inventory_proto protoreflect.FileDescriptor

const file_core_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x17core/v1/inventory.proto\x12\acore.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\x83\n" +
	"\n" +
	"\tInventory\x123\n" +
	"\x02id\x18\x01 \x01(\tB#\x9a\x84\x9e\x03\x1ebson:\"_id,omitempty\" json:\"id\"R\x02id\x12O\n" +
	"\finventory_id\x18\x02 \x01(\tB,\x9a\x84\x9e\x03'bson:\"inventory_id\" json:\"inventory_id\"R\vinventoryId\x12C\n" +
	"\ttenant_id\x18\x03 \x01(\tB&\x9a\x84\x9e\x03!bson:\"tenant_id\" json:\"tenant_id\"R\btenantId\x12G\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tB(\x9a\x84\x9e\x03#bson:\"product_id\" json:\"product_id\"R\tproductId\x12O\n" +
	"\fwarehouse_id\x18\x05 \x01(\tB,\x9a\x84\x9e\x03'bson:\"warehouse_id\" json:\"warehouse_id\"R\vwarehouseId\x12@\n" +
	"\bquantity\x18\x06 \x01(\x05B$\x9a\x84\x9e\x03\x1fbson:\"quantity\" json:\"quantity\"R\bquantity\x12@\n" +
	"\breserved\x18\a \x01(\x05B$\x9a\x84\x9e\x03\x1fbson:\"reserved\" json:\"reserved\"R\breserved\x12D\n" +
	"\tavailable\x18\b \x01(\x05B&\x9a\x84\x9e\x03!bson:\"available\" json:\"available\"R\tavailable\x12p\n" +
	"\blocation\x18\t \x01(\v2\x1a.core.v1.InventoryLocationB8\x9a\x84\x9e\x033bson:\"location,omitempty\" json:\"location,omitempty\"R\blocation\x12c\n" +
	"\fbatch_number\x18\n" +
	" \x01(\tB@\x9a\x84\x9e\x03;bson:\"batch_number,omitempty\" json:\"batch_number,omitempty\"R\vbatchNumber\x12k\n" +
	"\x0eserial_numbers\x18\v \x03(\tBD\x9a\x84\x9e\x03?bson:\"serial_numbers,omitempty\" json:\"serial_numbers,omitempty\"R\rserialNumbers\x12{\n" +
	"\vexpiry_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampB>\x9a\x84\x9e\x039bson:\"expiry_date,omitempty\" json:\"expiry_date,omitempty\"R\n" +
	"expiryDate\x12o\n" +
	"\rreceived_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampB.\x9a\x84\x9e\x03)bson:\"received_date\" json:\"received_date\"R\freceivedDate\x120\n" +
	"\x04cost\x18\x0e \x01(\x01B\x1c\x9a\x84\x9e\x03\x17bson:\"cost\" json:\"cost\"R\x04cost\x12c\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB(\x9a\x84\x9e\x03#bson:\"updated_at\" json:\"updated_at\"R\tupdatedAt\"\xe9\x01\n" +
	"\x11InventoryLocation\x12H\n" +
	"\x05aisle\x18\x01 \x01(\tB2\x9a\x84\x9e\x03-bson:\"aisle,omitempty\" json:\"aisle,omitempty\"R\x05aisle\x12H\n" +
	"\x05shelf\x18\x02 \x01(\tB2\x9a\x84\x9e\x03-bson:\"shelf,omitempty\" json:\"shelf,omitempty\"R\x05shelf\x12@\n" +
	"\x03bin\x18\x03 \x01(\tB.\x9a\x84\x9e\x03)bson:\"bin,omitempty\" json:\"bin,omitempty\"R\x03binB3Z1erp.localhost/internal/infra/model/core/v1;corev1b\x06proto3"

var (
	file_core_v1_inventory_proto_rawDescOnce sync.Once
	file_core_v1_inventory_proto_rawDescData []byte
)

func file_core_v1_inventory_proto_rawDescGZIP() []byte {
	file_core_v1_inventory_proto_rawDescOnce.Do(func() {
		file_core_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_inventory_proto_rawDesc), len(file_core_v1_inventory_proto_rawDesc)))
	})
	return file_core_v1_inventory_proto_rawDescData
}

var file_core_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_v1_inventory_proto_goTypes = []any{
	(*Inventory)(nil),             // 0: core.v1.Inventory
	(*InventoryLocation)(nil),     // 1: core.v1.InventoryLocation
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_core_v1_inventory_proto_depIdxs = []int32{
	1, // 0: core.v1.Inventory.location:type_name -> core.v1.InventoryLocation
	2, // 1: core.v1.Inventory.expiry_date:type_name -> google.protobuf.Timestamp
	2, // 2: core.v1.Inventory.received_date:type_name -> google.protobuf.Timestamp
	2, // 3: core.v1.Inventory.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_v1_inventory_proto_init() }
func file_core_v1_inventory_proto_init() {
	if File_core_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_inventory_proto_rawDesc), len(file_core_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_inventory_proto_goTypes,
		DependencyIndexes: file_core_v1_inventory_proto_depIdxs,
		MessageInfos:      file_core_v1_inventory_proto_msgTypes,
	}.Build()
	File_core_v1_inventory_proto = out.File
	file_core_v1_inventory_proto_goTypes = nil
	file_core_v1_inventory_proto_depIdxs = nil
}
