syntax = "proto3";

package event.v1;

option go_package = "erp.localhost/infra/model/event/v1;eventv1";

import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";
import "tagger/tagger.proto";
import "event/v1/types.proto";

message Message {
    string id = 1 [(tagger.tags) = "bson:\"id\" json:\"id\""]; // Message ID (UUID)
    string tenant_id = 2 [(tagger.tags) = "bson:\"tenant_id\" json:\"tenant_id\""]; // Multi-tenant isolation
    string entity_type = 3 [(tagger.tags) = "bson:\"entity_type,omitempty\" json:\"entity_type,omitempty\""]; // "user", "order", etc.
    string entity_id = 4 [(tagger.tags) = "bson:\"entity_id,omitempty\" json:\"entity_id,omitempty\""]; // "user_123", "order_456"
    google.protobuf.Timestamp timestamp = 5 [(tagger.tags) = "bson:\"timestamp\" json:\"timestamp\""]; // Event time
    event.v1.EventType event_type = 6 [(tagger.tags) = "bson:\"event_type\" json:\"event_type\""]; // "events.UserCreatedEvent"
    google.protobuf.Any event_data = 7 [(tagger.tags) = "bson:\"event_data\" json:\"event_data\""]; // Polymorphic event data
}

